// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://pl.yext.com' | (string & {});
};

export type Webhooks = NotifyReviewWebhookRequest | NotifySuggestionWebhookRequest;

/**
 * List of comments on the review
 */
export type PartnerReviewComments = Array<{
    /**
     * Id of the review comment
     */
    commentId: string;
    /**
     * Date and time that the review comment was posted in ISO-9601 format
     */
    timestamp: string;
    /**
     * The name of the user who posted the review comment
     */
    authorName: string;
    /**
     * The full text of the review comment
     */
    content: string;
    /**
     * Indicates whether the comment was made by the business owner
     */
    ownerResponse?: boolean;
}>;

export type PartnerReview = Array<{
    /**
     * A unique ID for each review, as assinged by you
     */
    reviewId: string;
    /**
     * The status of the review
     */
    status: 'ACTIVE' | 'SUPPRESSED';
    /**
     * Date and time that the review was posted in ISO-9601 format
     */
    timestamp: string;
    /**
     * The name of the user who posted the review
     */
    authorName: string;
    /**
     * The title of the review
     */
    title?: string;
    /**
     * The full text of the review
     */
    content?: string;
    /**
     * The URL where consumers can read the review
     */
    url: string;
    /**
     * The rating given by the review
     */
    rating?: string;
    /**
     * The maximum possible rating of a review on your site
     */
    maxRating?: string;
    /**
     * If present, the business owner has flagged the review a specific reason
     */
    flagReason?: 'INAPPROPRIATE_CONTENT' | 'SPAM' | 'NOT_LOCATION_RELATED';
    comments?: PartnerReviewComments;
    /**
     * Indicates whether the review was written in response to a request from a review_generation program
     */
    generated?: boolean;
}>;

export type ReviewNotification = {
    /**
     * Publisher Listing ID
     */
    listingId: string;
    /**
     * Total number of reviews on the listing, overall
     */
    total: string;
    /**
     * Official time the event occurred
     */
    timestamp: string;
    /**
     * The average rating across all reviews for this listing (of which there are total)
     */
    averageRating?: string;
    /**
     * A list containing one element - the updated review
     */
    reviews: PartnerReview;
};

export type PartnerSuggestion = {
    /**
     * A unique ID for each suggestion, as assigned by you
     */
    id: string;
    /**
     * The name of the listing field associated with the suggestion (e.g. main_phone, website_url)
     */
    field: string;
    /**
     * * ACCEPTED (the suggestion has been applied to the listing)
     * * PENDING (the suggestion is valid but has not been actioned on)
     * * REJECTED (the suggestion has been rejected)
     * * EXPIRED (the suggestion is no longer valid)'
     *
     */
    status: 'ACCEPTED' | 'PENDING' | 'REJECTED' | 'EXPIRED';
    /**
     * Date and time that the suggestion was created in ISO-9601 format
     */
    timestamp: string;
    /**
     * The existing field data
     */
    currentValue?: string;
    /**
     * The content of the suggestion. The type of this value should match the type structure of the field
     */
    proposedValue: string;
};

export type SuggestionNotification = {
    /**
     * Publisher Listing ID
     */
    listingId: string;
    eventType: 'SUGGESTION_CREATED' | 'SUGGESTION_UPDATED';
    /**
     * Official time the event occurred
     */
    timestamp: string;
    suggestion: PartnerSuggestion;
};

/**
 * Publisher api key
 *
 */
export type ApiKey = string;

export type NotifyReviewWebhookPayload = ReviewNotification;

export type NotifyReviewWebhookRequest = {
    body: NotifyReviewWebhookPayload;
    key: 'notifyReview';
    path?: never;
    query?: never;
};

export type NotifySuggestionWebhookPayload = SuggestionNotification;

export type NotifySuggestionWebhookRequest = {
    body: NotifySuggestionWebhookPayload;
    key: 'notifySuggestion';
    path?: never;
    query?: never;
};
