// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * List of comments on the review
 */
export const zPartnerReviewComments = z.array(z.object({
    commentId: z.string(),
    timestamp: z.string(),
    authorName: z.string(),
    content: z.string(),
    ownerResponse: z.boolean().optional()
}));

export const zPartnerReview = z.array(z.object({
    reviewId: z.string(),
    status: z.enum(['ACTIVE', 'SUPPRESSED']),
    timestamp: z.string(),
    authorName: z.string(),
    title: z.string().optional(),
    content: z.string().optional(),
    url: z.string(),
    rating: z.string().optional(),
    maxRating: z.string().optional(),
    flagReason: z.enum([
        'INAPPROPRIATE_CONTENT',
        'SPAM',
        'NOT_LOCATION_RELATED'
    ]).optional(),
    comments: zPartnerReviewComments.optional(),
    generated: z.boolean().optional()
}));

export const zReviewNotification = z.object({
    listingId: z.string(),
    total: z.string(),
    timestamp: z.string(),
    averageRating: z.string().optional(),
    reviews: zPartnerReview
});

export const zPartnerSuggestion = z.object({
    id: z.string(),
    field: z.string(),
    status: z.enum([
        'ACCEPTED',
        'PENDING',
        'REJECTED',
        'EXPIRED'
    ]),
    timestamp: z.string(),
    currentValue: z.string().optional(),
    proposedValue: z.string()
});

export const zSuggestionNotification = z.object({
    listingId: z.string(),
    eventType: z.enum(['SUGGESTION_CREATED', 'SUGGESTION_UPDATED']),
    timestamp: z.string(),
    suggestion: zPartnerSuggestion
});

/**
 * Publisher api key
 *
 */
export const zApiKey = z.string();

export const zNotifyReviewWebhookRequest = z.object({
    body: zReviewNotification.optional(),
    path: z.never().optional(),
    query: z.object({
        api_key: z.string().optional()
    }).optional()
});

export const zNotifySuggestionWebhookRequest = z.object({
    body: zSuggestionNotification.optional(),
    path: z.never().optional(),
    query: z.object({
        api_key: z.string().optional()
    }).optional()
});
