// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { PixelData, PixelErrors, PixelResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Pixel
 */
export const pixel = <ThrowOnError extends boolean = false>(options: Options<PixelData, ThrowOnError>): RequestResult<PixelResponses, PixelErrors, ThrowOnError> => (options.client ?? client).get<PixelResponses, PixelErrors, ThrowOnError>({ url: '/plpixel', ...options });
