// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://pixel.yext-pub.com' | (string & {});
};

/**
 * Publisher secure ID. This value will be provided to you.
 *
 */
export type Pid = string;

/**
 * Comma-separated list of Yext location Ids
 *
 */
export type Ids = string;

/**
 * Type of page where the event took place. Most commonly, you will use **serp** on the search results page, **detailspage** on the business profile page, and not use the others.
 *
 */
export type Source = 'serp' | 'mapbubble' | 'detailspage' | 'drivingdirections';

/**
 * Type of event that took place
 *
 */
export type Action = 'impression' | 'click';

/**
 * The search query that caused the SERP to be displayed. If your site’s search is powered by a single input field, then just provide that field.
 * * Required if **source** is **serp**
 * * The value of this field must be URL encoded
 *
 */
export type Query = string;

/**
 * Search queries that allow the user to specify a target location should pass the entered location in this parameter.  If your site allows the user inputs to enter both fields in "Find X near Y", "X" should be provided as "query" and "Y" should be provided as **querylocation**.
 * * Required if **source** is **serp**
 * * The value of this field must be URL encoded
 *
 */
export type Querylocation = string;

/**
 * The search rank of the identified listing in the organic results. The rank should be absolute (e.g., the first result on page 2 should have rank 11, assuming 10 results per page).
 * * Comma-separated list of integers, 1-indexed, parallel to ids.
 * * A rank of '5' in the first index would indicate that the first listing in the list appeared fifth in the organic results
 *
 */
export type Rank = string;

/**
 * Indicates which part of the page the user clicked on. For clicks on the SERP that send the user to the details page, you may optionally report a target of moreinfo rather than specifying a particular field.
 * If no appropriate value is available, please contact us.
 * * Required if **action** is **click**
 *
 */
export type Target = 'bios' | 'directions' | 'email' | 'events' | 'hours' | 'map' | 'mappin' | 'menus' | 'moreinfo' | 'name' | 'phone' | 'products' | 'reviews' | 'searchnearby' | 'share' | 'website';

/**
 * Indicates the Internet property where the event took place.
 * You should always provide this value if your listings are available on multiple platforms or properties (e.g., website, iPhone app, and Android app or publisher.example.com and local.publisher.com).
 * * This value does not have to be a domain name, but please choose something that’s likely to be unique.
 *
 */
export type Property = string;

/**
 * The user agent from the original web request.
 * * Required  if and only if making a server-side call to report a web page view
 *
 */
export type Useragent = string;

/**
 * A unique identifier for the IP address of the original web request, to be used for filtering erroneous traffic.
 * The IP address itself is preferred, but any arbitrary string (e.g., a hash of the IP address) is acceptable.
 * * Required if and only if making a server-side call
 *
 */
export type Userid = string;

/**
 * The URL of the original web request
 * * Required  if and only if making a server-side call to report a web page view
 *
 */
export type Pageurl = string;

/**
 * Any additional data you wish to include
 * For example, you may want to include details to indicate that this event was the result of someone printing a map or requesting driving directions, or to disambiguate between two different kinds of detail page impressions
 *
 */
export type Additional = string;

export type PixelData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Publisher secure ID. This value will be provided to you.
         *
         */
        pid: string;
        /**
         * Comma-separated list of Yext location Ids
         *
         */
        ids: string;
        /**
         * Type of page where the event took place. Most commonly, you will use **serp** on the search results page, **detailspage** on the business profile page, and not use the others.
         *
         */
        source: 'serp' | 'mapbubble' | 'detailspage' | 'drivingdirections';
        /**
         * Type of event that took place
         *
         */
        action: 'impression' | 'click';
        /**
         * The search query that caused the SERP to be displayed. If your site’s search is powered by a single input field, then just provide that field.
         * * Required if **source** is **serp**
         * * The value of this field must be URL encoded
         *
         */
        query?: string;
        /**
         * Search queries that allow the user to specify a target location should pass the entered location in this parameter.  If your site allows the user inputs to enter both fields in "Find X near Y", "X" should be provided as "query" and "Y" should be provided as **querylocation**.
         * * Required if **source** is **serp**
         * * The value of this field must be URL encoded
         *
         */
        querylocation?: string;
        /**
         * The search rank of the identified listing in the organic results. The rank should be absolute (e.g., the first result on page 2 should have rank 11, assuming 10 results per page).
         * * Comma-separated list of integers, 1-indexed, parallel to ids.
         * * A rank of '5' in the first index would indicate that the first listing in the list appeared fifth in the organic results
         *
         */
        rank?: string;
        /**
         * Indicates which part of the page the user clicked on. For clicks on the SERP that send the user to the details page, you may optionally report a target of moreinfo rather than specifying a particular field.
         * If no appropriate value is available, please contact us.
         * * Required if **action** is **click**
         *
         */
        target?: 'bios' | 'directions' | 'email' | 'events' | 'hours' | 'map' | 'mappin' | 'menus' | 'moreinfo' | 'name' | 'phone' | 'products' | 'reviews' | 'searchnearby' | 'share' | 'website';
        /**
         * Indicates the Internet property where the event took place.
         * You should always provide this value if your listings are available on multiple platforms or properties (e.g., website, iPhone app, and Android app or publisher.example.com and local.publisher.com).
         * * This value does not have to be a domain name, but please choose something that’s likely to be unique.
         *
         */
        property?: string;
        /**
         * The user agent from the original web request.
         * * Required  if and only if making a server-side call to report a web page view
         *
         */
        useragent?: string;
        /**
         * A unique identifier for the IP address of the original web request, to be used for filtering erroneous traffic.
         * The IP address itself is preferred, but any arbitrary string (e.g., a hash of the IP address) is acceptable.
         * * Required if and only if making a server-side call
         *
         */
        userid?: string;
        /**
         * The URL of the original web request
         * * Required  if and only if making a server-side call to report a web page view
         *
         */
        pageurl?: string;
        /**
         * Any additional data you wish to include
         * For example, you may want to include details to indicate that this event was the result of someone printing a map or requesting driving directions, or to disambiguate between two different kinds of detail page impressions
         *
         */
        additional?: string;
    };
    url: '/plpixel';
};

export type PixelErrors = {
    /**
     * Bad request (Incorrect Format)
     */
    400: unknown;
};

export type PixelResponses = {
    /**
     * Success
     */
    200: unknown;
};
