// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Publisher secure ID. This value will be provided to you.
 *
 */
export const zPid = z.string();

/**
 * Comma-separated list of Yext location Ids
 *
 */
export const zIds = z.string();

/**
 * Type of page where the event took place. Most commonly, you will use **serp** on the search results page, **detailspage** on the business profile page, and not use the others.
 *
 */
export const zSource = z.enum([
    'serp',
    'mapbubble',
    'detailspage',
    'drivingdirections'
]);

/**
 * Type of event that took place
 *
 */
export const zAction = z.enum(['impression', 'click']);

/**
 * The search query that caused the SERP to be displayed. If your site’s search is powered by a single input field, then just provide that field.
 * * Required if **source** is **serp**
 * * The value of this field must be URL encoded
 *
 */
export const zQuery = z.string();

/**
 * Search queries that allow the user to specify a target location should pass the entered location in this parameter.  If your site allows the user inputs to enter both fields in "Find X near Y", "X" should be provided as "query" and "Y" should be provided as **querylocation**.
 * * Required if **source** is **serp**
 * * The value of this field must be URL encoded
 *
 */
export const zQuerylocation = z.string();

/**
 * The search rank of the identified listing in the organic results. The rank should be absolute (e.g., the first result on page 2 should have rank 11, assuming 10 results per page).
 * * Comma-separated list of integers, 1-indexed, parallel to ids.
 * * A rank of '5' in the first index would indicate that the first listing in the list appeared fifth in the organic results
 *
 */
export const zRank = z.string();

/**
 * Indicates which part of the page the user clicked on. For clicks on the SERP that send the user to the details page, you may optionally report a target of moreinfo rather than specifying a particular field.
 * If no appropriate value is available, please contact us.
 * * Required if **action** is **click**
 *
 */
export const zTarget = z.enum([
    'bios',
    'directions',
    'email',
    'events',
    'hours',
    'map',
    'mappin',
    'menus',
    'moreinfo',
    'name',
    'phone',
    'products',
    'reviews',
    'searchnearby',
    'share',
    'website'
]);

/**
 * Indicates the Internet property where the event took place.
 * You should always provide this value if your listings are available on multiple platforms or properties (e.g., website, iPhone app, and Android app or publisher.example.com and local.publisher.com).
 * * This value does not have to be a domain name, but please choose something that’s likely to be unique.
 *
 */
export const zProperty = z.string();

/**
 * The user agent from the original web request.
 * * Required  if and only if making a server-side call to report a web page view
 *
 */
export const zUseragent = z.string();

/**
 * A unique identifier for the IP address of the original web request, to be used for filtering erroneous traffic.
 * The IP address itself is preferred, but any arbitrary string (e.g., a hash of the IP address) is acceptable.
 * * Required if and only if making a server-side call
 *
 */
export const zUserid = z.string();

/**
 * The URL of the original web request
 * * Required  if and only if making a server-side call to report a web page view
 *
 */
export const zPageurl = z.string();

/**
 * Any additional data you wish to include
 * For example, you may want to include details to indicate that this event was the result of someone printing a map or requesting driving directions, or to disambiguate between two different kinds of detail page impressions
 *
 */
export const zAdditional = z.string();

export const zPixelQuery = z.object({
    pid: z.string(),
    ids: z.string(),
    source: z.enum([
        'serp',
        'mapbubble',
        'detailspage',
        'drivingdirections'
    ]),
    action: z.enum(['impression', 'click']),
    query: z.string().optional(),
    querylocation: z.string().optional(),
    rank: z.string().optional(),
    target: z.enum([
        'bios',
        'directions',
        'email',
        'events',
        'hours',
        'map',
        'mappin',
        'menus',
        'moreinfo',
        'name',
        'phone',
        'products',
        'reviews',
        'searchnearby',
        'share',
        'website'
    ]).optional(),
    property: z.string().optional(),
    useragent: z.string().optional(),
    userid: z.string().optional(),
    pageurl: z.string().optional(),
    additional: z.string().optional()
});
