// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { MessageData, MessageErrors, MessageResponses } from './types.gen.js';
import { zMessageResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Chat: Message Endpoint
 *
 * Send messages and receive responses from a Yext Chat bot.
 */
export const message = <ThrowOnError extends boolean = false>(options: Options<MessageData, ThrowOnError>): RequestResult<MessageResponses, MessageErrors, ThrowOnError> => (options.client ?? client).post<MessageResponses, MessageErrors, ThrowOnError>({
    responseValidator: async (data) => await zMessageResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/chat/{botId}/message',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
