// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://cdn.yextapis.com/v2' | (string & {});
};

export type Message = {
    /**
     * Timestamp when the message was received, in ISO 8601 format.
     */
    timestamp?: string;
    /**
     * Either `USER` if the message was sent by the human user, or `BOT` if the message was sent by the chatbot.
     */
    source?: 'USER' | 'BOT';
    /**
     * The text of the message.
     */
    text?: string;
};

/**
 * A ULID representing the conversation between the user and the chatbot.
 */
export type ConversationId = string;

export type Notes = {
    /**
     * The current goal the chatbot has detected the user is trying to achieve.
     */
    currentGoal?: string;
    /**
     * The index of the step within the instructions of `currentGoal` that the chatbot is currently performing.
     * If the step is nested under a conditional `IF` step, it is represented with an array with multiple values.
     * E.g., if the `IF` step is the third step in the goal, and the bot is on the second step within the `IF` step, the value would be `[2, 1]`.
     *
     */
    currentStepIndices?: Array<number>;
    /**
     * The data that the chatbot has collected from the user so far.
     */
    collectedData?: {
        [key: string]: unknown;
    };
    /**
     * The search query that the chatbot predicted and ran to retrieve the `queryResult`.
     */
    searchQuery?: string;
    /**
     * The results returned in the Search, REST API call, or FUNCTION call using the `searchQuery`.
     */
    queryResult?: {
        [key: string]: unknown;
    };
    /**
     * The index of the message within `messages` when the `currentGoal` began.
     * This is important in some cases when the chatbot should not pull context from messages that are not part of the current goal.
     *
     */
    goalFirstMsgIndex?: number;
};

export type ResponseMeta = {
    /**
     * Unique ID for this request / response.
     */
    uuid?: string;
};

/**
 * List of errors and warnings.
 */
export type Error = Array<{
    /**
     * Code that uniquely identifies the error or warning.
     */
    code?: number;
    /**
     * Type of error.
     */
    type?: 'FATAL_ERROR' | 'NON_FATAL_ERROR' | 'WARNING';
    /**
     * Message explaining the problem.
     */
    message?: string;
}>;

export type AccountId = string;

/**
 * A date in `YYYYMMDD` format.
 */
export type V = string;

/**
 * The ID of the chatbot.
 */
export type BotId = string;

export type MessageData = {
    body?: {
        /**
         * List of messages representing the full conversation history.
         */
        messages?: Array<Message>;
        conversationId?: ConversationId;
        notes?: Notes;
        /**
         * Additional, user-defined information that is passed to the chatbot, and can be referenced in the instruction flow.
         */
        context?: {
            [key: string]: unknown;
        };
        /**
         * The version of chatbot. Defaults to `LATEST`.
         */
        version?: 'LATEST' | 'STAGING' | 'PRODUCTION';
    };
    path: {
        accountId: string;
        /**
         * The ID of the chatbot.
         */
        botId: string;
    };
    query?: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v?: string;
    };
    url: '/accounts/{accountId}/chat/{botId}/message';
};

export type MessageErrors = {
    /**
     * Message Response
     *
     * Error Response
     */
    default: {
        meta?: ResponseMeta;
        error?: Error;
    };
};

export type MessageError = MessageErrors[keyof MessageErrors];

export type MessageResponses = {
    /**
     * MessageResponse
     *
     * Message Response
     */
    200: {
        meta?: ResponseMeta;
        response?: {
            conversationId?: ConversationId;
            message?: Message;
            notes?: Notes;
        };
    };
};

export type MessageResponse = MessageResponses[keyof MessageResponses];
