// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zMessage = z.object({
    timestamp: z.string().optional(),
    source: z.enum(['USER', 'BOT']).optional(),
    text: z.string().optional()
});

/**
 * A ULID representing the conversation between the user and the chatbot.
 */
export const zConversationId = z.string();

export const zNotes = z.object({
    currentGoal: z.string().optional(),
    currentStepIndices: z.array(z.int()).optional(),
    collectedData: z.record(z.string(), z.unknown()).optional(),
    searchQuery: z.string().optional(),
    queryResult: z.record(z.string(), z.unknown()).optional(),
    goalFirstMsgIndex: z.int().optional()
});

export const zResponseMeta = z.object({
    uuid: z.string().optional()
});

/**
 * List of errors and warnings.
 */
export const zError = z.array(z.object({
    code: z.int().optional(),
    type: z.enum([
        'FATAL_ERROR',
        'NON_FATAL_ERROR',
        'WARNING'
    ]).optional(),
    message: z.string().optional()
}));

export const zAccountId = z.string();

/**
 * A date in `YYYYMMDD` format.
 */
export const zV = z.string();

/**
 * The ID of the chatbot.
 */
export const zBotId = z.string();

export const zMessageBody = z.object({
    messages: z.array(zMessage).optional(),
    conversationId: zConversationId.optional(),
    notes: zNotes.optional(),
    context: z.record(z.string(), z.unknown()).optional(),
    version: z.enum([
        'LATEST',
        'STAGING',
        'PRODUCTION'
    ]).optional()
});

export const zMessagePath = z.object({
    accountId: z.string(),
    botId: z.string()
});

export const zMessageQuery = z.object({
    v: z.string().optional()
});

/**
 * MessageResponse
 *
 * Message Response
 */
export const zMessageResponse = z.object({
    meta: zResponseMeta.optional(),
    response: z.object({
        conversationId: zConversationId.optional(),
        message: zMessage.optional(),
        notes: zNotes.optional()
    }).optional()
});
