// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { AutocompleteData, AutocompleteErrors, AutocompleteResponses, FiltersearchData, FiltersearchErrors, FiltersearchResponses, GenerateAnswerData, GenerateAnswerErrors, GenerateAnswerResponses, QueryData, QueryErrors, QueryResponses, VerticalAutocompleteData, VerticalAutocompleteErrors, VerticalAutocompleteResponses, VerticalQueryData, VerticalQueryErrors, VerticalQueryResponses } from './types.gen.js';
import { zAutocompleteResponse, zFiltersearchResponse, zGenerateAnswerResponse, zQueryResponse, zVerticalAutocompleteResponse, zVerticalQueryResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Universal Search: Autocomplete
 *
 * Retrieve a list of suggested queries across all verticals in the experience based on the characters already typed by the user. This API is meant to be hit after each keystroke.
 */
export const autocomplete = <ThrowOnError extends boolean = false>(options: Options<AutocompleteData, ThrowOnError>): RequestResult<AutocompleteResponses, AutocompleteErrors, ThrowOnError> => (options.client ?? client).get<AutocompleteResponses, AutocompleteErrors, ThrowOnError>({
    responseValidator: async (data) => await zAutocompleteResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/autocomplete',
    ...options
});

/**
 * Universal Search: Query
 *
 * Search for entities across all verticals within a Search experience.  Modules are returned for all verticals with relevant entities. Further fine tuning and filtering of the results can then be done using the vertical query endpoint. A maximum of 50 verticals can be queried with this endpoint.
 *
 * In order prevent bot traffic from using Search API Capacity, you must integrate with the Search API from the front end of your application.  The Search API's Bot Detection feature requires the API to be called directly from the end-user's web browser.  If you must integrate with the Search API via another mechanism, all traffic will be charged against your search capacity and some features of Search Analytics, such as Search Terms and Search Term Clustering may not work.
 *
 */
export const query = <ThrowOnError extends boolean = false>(options: Options<QueryData, ThrowOnError>): RequestResult<QueryResponses, QueryErrors, ThrowOnError> => (options.client ?? client).get<QueryResponses, QueryErrors, ThrowOnError>({
    responseValidator: async (data) => await zQueryResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/query',
    ...options
});

/**
 * Vertical Search: Autocomplete
 *
 * Retrieve a list of suggested queries for the selected vertical based on the characters already typed by the user or the most popular queries when no user input is given.
 */
export const verticalAutocomplete = <ThrowOnError extends boolean = false>(options: Options<VerticalAutocompleteData, ThrowOnError>): RequestResult<VerticalAutocompleteResponses, VerticalAutocompleteErrors, ThrowOnError> => (options.client ?? client).get<VerticalAutocompleteResponses, VerticalAutocompleteErrors, ThrowOnError>({
    responseValidator: async (data) => await zVerticalAutocompleteResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/vertical/autocomplete',
    ...options
});

/**
 * Vertical Search: Query
 *
 * Search for entities within the selected vertical.  Vertical query allows for fine tuning of the search using filters, facets and sorts passed in through the API.
 *
 * In order prevent bot traffic from using Search API Capacity, you must integrate with the Search API from the front end of your application.  The Search API's Bot Detection feature requires the API to be called directly from the end-user's web browser.  If you must integrate with the Search API via another mechanism, all traffic will be charged against your search capacity and some features of Search Analytics, such as Search Terms and Search Term Clustering may not work.
 *
 */
export const verticalQuery = <ThrowOnError extends boolean = false>(options: Options<VerticalQueryData, ThrowOnError>): RequestResult<VerticalQueryResponses, VerticalQueryErrors, ThrowOnError> => (options.client ?? client).get<VerticalQueryResponses, VerticalQueryErrors, ThrowOnError>({
    responseValidator: async (data) => await zVerticalQueryResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/vertical/query',
    ...options
});

/**
 * Vertical Search: Filter Search
 *
 * Retrieve a list of potential filters that match the user's input up to that point.  This differs from query suggest by only returning the names of filters that can be searched rather than the broader corpus of suggested queries.
 */
export const filtersearch = <ThrowOnError extends boolean = false>(options: Options<FiltersearchData, ThrowOnError>): RequestResult<FiltersearchResponses, FiltersearchErrors, ThrowOnError> => (options.client ?? client).get<FiltersearchResponses, FiltersearchErrors, ThrowOnError>({
    responseValidator: async (data) => await zFiltersearchResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/filtersearch',
    ...options
});

/**
 * Answer: Generate
 *
 *
 * Leverages large language models (LLMs) to deliver generated summaries based on search results.
 *
 * This endpoint works with the Universal/Vertical Search endpoint, which provides the search results for the LLM to analyze and generate direct answers.
 *
 */
export const generateAnswer = <ThrowOnError extends boolean = false>(options: Options<GenerateAnswerData, ThrowOnError>): RequestResult<GenerateAnswerResponses, GenerateAnswerErrors, ThrowOnError> => (options.client ?? client).post<GenerateAnswerResponses, GenerateAnswerErrors, ThrowOnError>({
    responseValidator: async (data) => await zGenerateAnswerResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/search/generateAnswer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
