// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://cdn.yextapis.com/v2' | (string & {});
};

export type ResponseMeta = {
    /**
     * Unique ID for this request / response.
     */
    uuid?: string;
};

export type ResponseError = {
    name?: string;
    /**
     * Code that uniquely identifies the error or warning.
     *
     */
    code?: number;
    type?: 'FATAL_ERROR' | 'NON_FATAL_ERROR' | 'WARNING';
    /**
     * Message explaining the problem.
     */
    message?: string;
};

export type ResponseMetaWithError = ResponseMeta & {
    /**
     * List of errors and warnings.
     */
    errors?: Array<ResponseError>;
};

/**
 * ID of the account associated with this Search experience
 */
export type BusinessId = number;

/**
 * UUID for the query
 */
export type QueryId = string;

/**
 * String key that uniquely identifies the vertical.
 */
export type VerticalConfigId = string;

/**
 * The number of entities within the vertical that are relevant to the user's query.
 *
 */
export type ResultCount = number;

export type Entity = {
    /**
     * The data containing the main content of the entity. The format of the data is dependent on the entity type.
     *
     */
    data?: {
        [key: string]: unknown;
    };
    /**
     * A map from fieldId to highlighted element.
     *
     */
    highlightedFields?: {
        [key: string]: unknown;
    };
    /**
     * The distance in meters between the entity and the query's location bias.
     *
     */
    distance?: number;
    /**
     * The distance in meters between the entity and the filter applied to the query.
     *
     */
    distanceFromFilter?: number;
};

/**
 * The individual entity results that contain metadata about the entity as well as the fully rendered profiles.
 *
 */
export type Results = Array<Entity>;

/**
 * The filter, in the filter format, that was applied.
 * <br><br>
 * For example: `"c_exampleFieldId": { $eq": "Search" }`
 *
 */
export type Filter = {
    [key: string]: unknown;
};

/**
 * A list of the filters that were inferred from the user's query and applied at search time.
 */
export type AppliedQueryFilters = Array<{
    /**
     * The display name of the field to which the filter belongs.
     */
    displayKey?: string;
    /**
     * The value of the filter.
     */
    displayValue?: string;
    filter?: Filter;
    type?: 'FIELD_VALUE' | 'PLACE' | 'INTENT';
    /**
     * Object containing additional details relevant to the filter such as additional details about the place for `PLACE` type filters. The format of the data is dependent on the filter type.
     *
     */
    details?: {
        [key: string]: unknown;
    };
}>;

/**
 * The results and metadata pertaining to a single vertical relevant to the user's query.
 */
export type Module = {
    verticalConfigId?: VerticalConfigId;
    resultCount?: ResultCount;
    /**
     * Deprecated.
     */
    encodedState?: string;
    results?: Results;
    appliedQueryFilters?: AppliedQueryFilters;
};

/**
 * List of results for each vertical that was relevant to the query, returned in the order of relevance.
 */
export type Modules = Array<Module>;

export type FailedVertical = {
    verticalConfigId?: VerticalConfigId;
    /**
     * An identifier for the type of error causing the failure.
     *
     */
    errorType?: 'TIMEOUT' | 'BACKEND_ERROR' | 'INVALID_CONFIG' | 'INVALID_QUERY';
    details?: {
        /**
         * An HTTP response status code indicating the completion status of the request.
         *
         */
        responseCode?: number;
        /**
         * Message explaining the error.
         */
        description?: string;
    };
    /**
     * A measure of query duration, recorded in milliseconds.
     *
     */
    queryDurationMillis?: number;
};

/**
 * Contains error information when one or more verticals fail to return results.
 *
 */
export type FailedVerticals = Array<FailedVertical>;

/**
 * Information that is estimated to directly answer the question of the query.
 *
 */
export type DirectAnswer = {
    /**
     * Type of the direct answer, such as `FIELD_VALUE` or `FEATURED_SNIPPET`.
     *
     */
    type?: string;
    /**
     * The data containing the main content of the direct answer. The format of the data is dependent on the direct answer type.
     *
     */
    answer?: {
        [key: string]: unknown;
    };
    /**
     * An optional item that is related to the direct answer. For Knowledge Manager verticals, related items will typically be entities.
     *
     */
    relatedItem?: {
        verticalConfigId?: VerticalConfigId;
        /**
         * The data of the related item, which should be in the same shape (with possibly extra fields) as an item that appears in a section of results from the same vertical in universal search.
         *
         */
        data?: {
            [key: string]: unknown;
        };
    };
};

/**
 * Highlighting instructions for a field value, containing the original value of the field and all sections of the value that should be highlighted.
 *
 */
export type HighlightedValue = {
    /**
     * The original value of the field.
     *
     */
    value?: string;
    /**
     * The list of matched substrings within the value to highlight.
     *
     */
    matchedSubstrings?: Array<{
        /**
         * The zero indexed offset from the start of the value where the highlight starts.
         *
         */
        offsets?: number;
        /**
         * The length of the highlight.
         *
         */
        length?: number;
    }>;
};

/**
 * SpellCheck information that may correct the user's query.
 */
export type SpellCheck = {
    /**
     * The unedited, original query from the request.
     */
    originalQuery?: string;
    correctedQuery?: HighlightedValue;
    /**
     * The type of SpellCheck suggestion.
     * <br><br>
     * `SUGGEST` is often used for "Did you mean..."
     * <br>
     * `AUTOCORRECT` is often used for "Showing results for ... instead of ..."
     * <br>
     * `COMBINE` is often used for "Including results for ..."
     * <br><br>
     *
     */
    type?: 'SUGGEST' | 'AUTOCORRECT' | 'COMBINE';
};

/**
 * Information about geographical location biases used in the search.
 */
export type LocationBias = {
    /**
     * The geographic coordinate, latitude, used to bias the search.
     */
    latitude?: number;
    /**
     * The geographic coordinate, latitude, used to bias the search.
     */
    longitude?: number;
    /**
     * The display name of the location.
     */
    locationDisplayName?: string;
    /**
     * The accuracy of the location bias used for the search.
     * <br><br>
     * `DEVICE` is based on the user's device (passed in via the request param)
     * <br>
     * `IP` is based on the request's IP
     * <br>
     *
     */
    accuracy?: 'IP' | 'DEVICE' | 'UNKNOWN';
};

export type Facets = {
    /**
     * The field identifier for the field being searched.
     */
    fieldId?: string;
    /**
     * The display name for the field being searched.
     */
    displayName?: string;
    options?: Array<{
        /**
         * The display name for the Facet option.
         */
        displayName?: string;
        /**
         * The number of entities within the vertical that are relevant to this Facet option.
         */
        count?: number;
        /**
         * A boolean indicator of whether this Facet option was used to filter results in the response.
         */
        isSelected?: boolean;
        filter?: Filter;
    }>;
};

/**
 * Items in array each represent a particular intent expressed in the user's query. Example: `NEAR_ME`
 *
 */
export type SearchIntents = Array<string>;

export type GenerateAnswerRequest = {
    /**
     * ID of the search associated to the results.
     */
    searchId: string;
    /**
     * The search term that was used to generate results.
     */
    searchTerm: string;
    results: Module | {
        verticals?: Modules;
    };
};

export type AccountId = string;

/**
 * A date in `YYYYMMDD` format.
 */
export type V = string;

/**
 * String key that uniquely identifies the Search experience.
 */
export type ExperienceKey = string;

/**
 * The locale code of the experience (e.g. `en_GB`).
 */
export type Locale = string;

/**
 * The partial search term from the user.
 */
export type AutocompleteInput = string;

/**
 * Number of autocomplete results to return.
 */
export type AutocompleteLimit = number;

/**
 * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
 */
export type Version = string;

/**
 * The locale code of the experience (e.g. `en_GB`). Only returns entities that have an entity profile associated with this locale.
 */
export type QueryLocale = string;

/**
 * The search term of the user.
 */
export type RequiredInput = string;

/**
 * The user's location as a comma separated latitude and longitude (e.g. `"40.740957,-73.987565"`).
 */
export type Location = string;

/**
 * UUID used to track session state when cookies are blocked.
 */
export type SessionId = string;

/**
 * JSON object specifying the limit for each vertical.  Each key is a vertical key and the value for each of those keys is a number 1-50 that denotes the limit for that vertical. This parameter should be provided as a URL-encoded string containing a JSON object.
 */
export type UniversalLimit = string;

/**
 * String value that is logged to analytics denoting the trigger for the query.
 * Options include:
 * * `suggest`, sent if the query is triggered from a spelling correction.
 * * `initialize`, sent if the query is being triggered by a default initial search (in other words, the user did not enter query).
 *
 */
export type QueryTrigger = string;

/**
 * Context is an arbitrary JSON object that is passed to query rules to be used for triggering rules as well as passing data to those rules. This parameter should be provided as a URL-encoded string containing a JSON object.
 */
export type Context = string;

/**
 * The URL of the webpage that directed to the page this request was made from.
 */
export type ReferrerPageUrl = string;

/**
 * If true the query will skip spell checking.
 */
export type SkipSpellCheck = boolean;

/**
 * A comma-separated list of verticals (e.g. `"people,locations"`). If specified, only results from these verticals will be returned.
 */
export type RestrictVerticals = string;

/**
 * When set to true, ignores any Query Rules that would otherwise affect the results. Defaults to false.
 */
export type IgnoreQueryRules = boolean;

/**
 * UUID of the query; recommended when moving through results, to associate multiple requests to the same query.
 */
export type QueryId2 = string;

/**
 * Indicates where the query is coming from (e.g. `"HOME_HEADER"` or `"TICKET_FORM"`). Can be used in Analytics reports via the `Integration Source` dimension. Defaults to `"STANDARD"`.
 */
export type Source = string;

/**
 * The version of the Search UI used for this request. Deprecated.
 */
export type JsLibVersion = string;

/**
 * String key that uniquely identifies the vertical.
 */
export type VerticalKey = string;

/**
 * The search term of the user.
 */
export type VerticalInput = string;

/**
 * Radius (in meters) that should be applied to any location filter that does not already have an explicit radius.
 */
export type LocationRadius = string;

/**
 * Number of results to return.
 */
export type Limit = number;

/**
 * Number of results to skip. Used to move through results.
 */
export type Offset = number;

/**
 * This parameter represents one or more filtering conditions that are applied to the set of entities that would otherwise be returned. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * For example, if the filter JSON is `{"name":{"$eq":"John"}}`, then the filters param after URL-encoding will be: `filters=%7B%22name%22%3A%7B%22%24eq%22%3A%22John%22%7D%7D`
 *
 * **Basic Filter Structure**
 *
 * The filter object at its core consists of a *matcher*, a *field*, and an *argument*.
 *
 * For example, in the following filter JSON:
 *
 * ```
 * {
 * "name":{
 * "$eq":"John"
 * }
 * }
 * ```
 *
 * `$eq` is the *matcher*, or filtering operation (equals, in this example),
 *
 * `name` is the *field* being filtered by, and
 *
 * `John` is *value* to be matched against.
 *
 * **Combining Multiple Filters**
 *
 * Multiple filters can be combined to form a conjunction (AND) of disjunctions (ORs) using the *combinators* `$and` and `$or`.  For example:
 * ```
 * {
 * "$and": [
 * {
 * "$or": [
 * {
 * "firstName": {
 * "$eq": "Jane"
 * }
 * },
 * {
 * "firstName": {
 * "$eq": "John"
 * }
 * }
 * ]
 * },
 * {
 * "lastName": {
 * "$eq": "Smith"
 * }
 * }
 * ]
 * }
 * ```
 * Any filter that is the only item in its respective combinator may omit the combinator as is done with the lastName above.
 *
 * **Filter Negation**
 *
 * Certain filter types may be negated. For example:
 *
 * ```
 * {
 * "$not": {
 * "name": {
 * "$eq": "John"
 * }
 * }
 * }
 * ```
 *
 * This can also be written more simply with a `!` in the `$eq` parameter. The following filter would have the same effect:
 *
 * ```
 * {
 * "name":{
 * "!$eq":"John"
 * }
 * }
 * ```
 *
 * **TEXT**
 *
 * The `TEXT` filter type is supported for text fields. (e.g., **`name`**, **`countryCode`**)
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq (equals)</th>
 * <th>
 *
 * {
 * "countryCode":{
 * "$eq":"US"
 * }
 * },
 * {
 * "countryCode":{
 * "!$eq":"US"
 * }
 * }
 *
 * Supports negation. Case insensitive.
 * </tr>
 * <tr>
 * </table>
 *
 * **BOOLEAN**
 *
 *
 * The BOOLEAN filter type is supported for boolean fields and Yes / No custom fields.
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * {
 * "isFreeEvent": {
 * "$eq": true
 * }
 * }
 *
 * For booleans, the filter takes a boolean value, not a string.
 * Supports negation.
 * </tr>
 * </table>
 *
 * **OPTION**
 *
 * The OPTION filter type is supported for option custom fields and fields that have a predetermined list of valid values.
 *
 * *e.g., **`eventStatus`**, **`gender`**, `SINGLE_OPTION` and `MULTI_OPTION` types of custom fields.*
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * Matching is case insensitive and insensitive to consecutive whitespace.
 *
 * e.g., "XYZ 123" matches "xyz       123"
 *
 * {
 * "eventStatus": {
 * "$eq": "SCHEDULED"
 * }
 * }
 * </table>
 *
 * **INTEGER, FLOAT, DATE, DATETIME, and TIME**
 *
 * These filter types are strictly ordered -- therefore, they support the following matchers:
 * - Equals
 * - Less Than / Less Than or Equal To
 * - Greater Than / Greater Than or Equal To
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * Equals
 *
 * {
 * "ageRange.maxValue": {
 * "$eq": "80"
 * }
 * }
 *
 * Supports negation.
 *
 * </tr>
 * <tr>
 * <th>$lt</th>
 * <th>
 *
 * Less than
 *
 * {
 * "time.start": {
 * "$lt": "2018-08-28T05:56"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$gt</th>
 * <th>
 *
 * Greater than
 *
 * {
 * "ageRange.maxValue": {
 * "$gt": "50"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$le</th>
 * <th>
 *
 * Less than or equal to
 *
 * {
 * "ageRange.maxValue": {
 * "$le": "40"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$ge</th>
 * <th>
 *
 * Greater than or equal to
 *
 * {
 * "time.end": {
 * "$ge":  "2018-08-28T05:56"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$between</th>
 * <th>
 *
 * An array that must contain exactly two elements with which the result is between.
 *
 * {
 * "time.end": {
 * "$between":  ["2018-08-28T05:56", "2018-08-29T05:56"]
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>Combinations</th>
 * <th>
 *
 * In addition to between, it is possible to combine multiple matchers for a result similar to an "and" operation:
 *
 * {
 * "ageRange.maxValue" : {
 * "$gt" : 10,
 * "$lt": 20
 * }
 * }
 *
 * </tr>
 * </table>
 *
 */
export type Filters = string;

/**
 * This parameter represents the state of the currently checked facet options. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * The JSON object contains a key for each facet category that has a checked facet option.  The value for each of these keys is an array of Filter objects that describe the filter that is applied by the facet option.
 *
 * At the moment, facet options only support `$eq`.
 *
 * For example, if `Engineering` was checked under the `Category` facet and `Chicago` and `New York` are checked under the `Job Location` facet, the `facetFilters` would look like:
 * ```
 * {
 * "c_jobCategory": [
 * {
 * "c_jobCategory": {
 * "$eq": "Engineering"
 * }
 * }
 * ],
 * "c_jobLocation": [
 * {
 * "c_jobLocation": {
 * "$eq": "Chicago"
 * }
 * },
 * {
 * "c_jobLocation": {
 * "$eq": "New York"
 * }
 * }
 * ]
 * }
 * ```
 *
 */
export type FacetFilters = string;

/**
 * Whether facets should be computed for this vertical query.
 */
export type RetrieveFacets = boolean;

/**
 * This parameter overrides the sort options that are configured on the experience configuration.  This parameter should be provided as a URL-encoded string containing a JSON array.
 *
 * The input is a JSON array containing each of the sort options in the order in which they should be applied.
 *
 * Each sort options must contain a `type`
 *
 * <table style="width:100%">
 * <tr>
 * <th>Type</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>RELEVANCE</th>
 * <th>Sorts based on relevance according to the algorithm and, when relevant, location bias</th>
 * </tr>
 * <tr>
 * <th>ENTITY_DISTANCE</th>
 * <th>Sorts based on entity distance alone</th>
 * </tr>
 * <tr>
 * <th>FIELD</th>
 * <th>sorts based on a field with the direction specified</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * If the `type` is `FIELD` the sort options must also specify `field` which is the api name of the field to sort on.
 *
 * Finally, if the `type` is `FIELD` the sort options must also specify the `direction`.
 *
 * <table style="width:100%">
 * <tr>
 * <th>Direction</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>ASC</th>
 * <th>Sorts in ascending order.  For numbers this is low to high. For text this is alphabetical.  For dates this is chronological order.</th>
 * </tr>
 * <tr>
 * <th>DESC</th>
 * <th>Sorts in ascending order.  For numbers this is high to low. For text this is reverse alphabetical.  For dates this is reverse chronological order.</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * **Examples**
 * ```
 * [
 * {
 * "type": "FIELD",
 * "direction": "ASC",
 * "field": "startDate"
 * },
 * {
 * "type": "RELEVANCE",
 * "direction": "ASC"
 * }
 * ]
 * ```
 *
 */
export type SortBys = string;

/**
 * String key that uniquely identifies the vertical to scope the filter search request to.
 */
export type FilterSearchVerticalKey = string;

/**
 * This parameter represents the parameters that should be used for filter search. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * Filter search uses the user's input string to find a set of existing filters that match the user's input query for the fields provided in the parameters.
 *
 * The JSON object must have a `fields` property made up of a list of `FilterField` objects that have the following properties:
 *
 * <table style="width:100%">
 * <tr>
 * <th>Property</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>fieldId</th>
 * <th>The api name of the field.</th>
 * </tr>
 * <tr>
 * <th>entityTypeId</th>
 * <th>The api name for the entity type the filter belongs to.</th>
 * </tr>
 * <tr>
 * <th>shouldFetchEntities</th>
 * <th>Optional boolean.  If true, entities matching each filter will be returned inline with the filter.</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * Additionally, there is an optional boolean property `sectioned`.  If set to true, the matching filters will be returned in a separate section per field.  By default, they are all returned in the same section.
 *
 */
export type SearchParameters = string;

/**
 * This parameter represents any values which should not be returned. This parameter should be provided as a URL-encoded string containing a JSON array, where each entry of the array is a JSON object representing a field and an excluded value for that field. For example:
 * ```
 * [
 * {
 * "name": {
 * "$eq": "John"
 * }
 * },
 * {
 * "c_jobCategory": {
 * "$eq": "Engineering"
 * }
 * }
 * ]
 * ```
 *
 */
export type Excluded = string;

export type AutocompleteData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`).
         */
        locale: string;
        /**
         * The partial search term from the user.
         */
        input?: string;
        /**
         * Number of autocomplete results to return.
         */
        limit?: number;
        /**
         * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
         */
        version?: string;
    };
    url: '/accounts/{accountId}/search/autocomplete';
};

export type AutocompleteErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type AutocompleteError = AutocompleteErrors[keyof AutocompleteErrors];

export type AutocompleteResponses = {
    /**
     * AutocompleteResponse
     *
     * Autocomplete Request Response
     */
    200: {
        input?: {
            /**
             * The exact user input that triggered the autocomplete.
             *
             */
            value?: string;
            /**
             * List of query intents that the input has been tagged with.
             *
             */
            queryIntents?: Array<string>;
        };
        /**
         * The list of autocomplete results computed from the user's input.
         *
         */
        results?: Array<{
            /**
             * The plain text version of the autocomplete result.
             *
             */
            value?: string;
            /**
             * The list of matched substrings within the value to highlight.
             *
             */
            matchedSubstrings?: Array<{
                /**
                 * The zero indexed offset from the start of the value where the highlight starts.
                 *
                 */
                offsets?: number;
                /**
                 * The length of the highlight.
                 *
                 */
                length?: number;
            }>;
            /**
             * List of query intents that the input has been tagged with.
             *
             */
            queryIntents?: Array<string>;
            /**
             * List of verticals that the autocomplete result is derived from. For results coming from universal search, this field will be blank.
             *
             */
            verticalKeys?: Array<string>;
        }>;
    };
};

export type AutocompleteResponse = AutocompleteResponses[keyof AutocompleteResponses];

export type QueryData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`). Only returns entities that have an entity profile associated with this locale.
         */
        locale: string;
        /**
         * The search term of the user.
         */
        input: string;
        /**
         * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
         */
        version?: string;
        /**
         * The user's location as a comma separated latitude and longitude (e.g. `"40.740957,-73.987565"`).
         */
        location?: string;
        /**
         * UUID used to track session state when cookies are blocked.
         */
        session_id?: string;
        /**
         * JSON object specifying the limit for each vertical.  Each key is a vertical key and the value for each of those keys is a number 1-50 that denotes the limit for that vertical. This parameter should be provided as a URL-encoded string containing a JSON object.
         */
        limit?: string;
        /**
         * String value that is logged to analytics denoting the trigger for the query.
         * Options include:
         * * `suggest`, sent if the query is triggered from a spelling correction.
         * * `initialize`, sent if the query is being triggered by a default initial search (in other words, the user did not enter query).
         *
         */
        queryTrigger?: string;
        /**
         * Context is an arbitrary JSON object that is passed to query rules to be used for triggering rules as well as passing data to those rules. This parameter should be provided as a URL-encoded string containing a JSON object.
         */
        context?: string;
        /**
         * The URL of the webpage that directed to the page this request was made from.
         */
        referrerPageUrl?: string;
        /**
         * If true the query will skip spell checking.
         */
        skipSpellCheck?: boolean;
        /**
         * A comma-separated list of verticals (e.g. `"people,locations"`). If specified, only results from these verticals will be returned.
         */
        restrictVerticals?: string;
        /**
         * When set to true, ignores any Query Rules that would otherwise affect the results. Defaults to false.
         */
        ignoreQueryRules?: boolean;
        /**
         * UUID of the query; recommended when moving through results, to associate multiple requests to the same query.
         */
        queryId?: string;
        /**
         * Indicates where the query is coming from (e.g. `"HOME_HEADER"` or `"TICKET_FORM"`). Can be used in Analytics reports via the `Integration Source` dimension. Defaults to `"STANDARD"`.
         */
        source?: string;
        /**
         * The version of the Search UI used for this request. Deprecated.
         */
        jsLibVersion?: string;
    };
    url: '/accounts/{accountId}/search/query';
};

export type QueryErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type QueryError = QueryErrors[keyof QueryErrors];

export type QueryResponses = {
    /**
     * UniversalQueryResponse
     *
     * Universal Query Response
     */
    200: {
        meta?: ResponseMeta;
        response?: {
            businessId?: BusinessId;
            queryId?: QueryId;
            modules?: Modules;
            failedVerticals?: FailedVerticals;
            directAnswer?: DirectAnswer;
            spellCheck?: SpellCheck;
            locationBias?: LocationBias;
        };
    };
};

export type QueryResponse = QueryResponses[keyof QueryResponses];

export type VerticalAutocompleteData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * String key that uniquely identifies the vertical.
         */
        verticalKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`).
         */
        locale: string;
        /**
         * The partial search term from the user.
         */
        input?: string;
        /**
         * Number of autocomplete results to return.
         */
        limit?: number;
        /**
         * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
         */
        version?: string;
    };
    url: '/accounts/{accountId}/search/vertical/autocomplete';
};

export type VerticalAutocompleteErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type VerticalAutocompleteError = VerticalAutocompleteErrors[keyof VerticalAutocompleteErrors];

export type VerticalAutocompleteResponses = {
    /**
     * AutocompleteResponse
     *
     * Autocomplete Request Response
     */
    200: {
        input?: {
            /**
             * The exact user input that triggered the autocomplete.
             *
             */
            value?: string;
            /**
             * List of query intents that the input has been tagged with.
             *
             */
            queryIntents?: Array<string>;
        };
        /**
         * The list of autocomplete results computed from the user's input.
         *
         */
        results?: Array<{
            /**
             * The plain text version of the autocomplete result.
             *
             */
            value?: string;
            /**
             * The list of matched substrings within the value to highlight.
             *
             */
            matchedSubstrings?: Array<{
                /**
                 * The zero indexed offset from the start of the value where the highlight starts.
                 *
                 */
                offsets?: number;
                /**
                 * The length of the highlight.
                 *
                 */
                length?: number;
            }>;
            /**
             * List of query intents that the input has been tagged with.
             *
             */
            queryIntents?: Array<string>;
            /**
             * List of verticals that the autocomplete result is derived from. For results coming from universal search, this field will be blank.
             *
             */
            verticalKeys?: Array<string>;
        }>;
    };
};

export type VerticalAutocompleteResponse = VerticalAutocompleteResponses[keyof VerticalAutocompleteResponses];

export type VerticalQueryData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * String key that uniquely identifies the vertical.
         */
        verticalKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`). Only returns entities that have an entity profile associated with this locale.
         */
        locale: string;
        /**
         * The search term of the user.
         */
        input?: string;
        /**
         * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
         */
        version?: string;
        /**
         * The user's location as a comma separated latitude and longitude (e.g. `"40.740957,-73.987565"`).
         */
        location?: string;
        /**
         * Radius (in meters) that should be applied to any location filter that does not already have an explicit radius.
         */
        locationRadius?: string;
        /**
         * UUID used to track session state when cookies are blocked.
         */
        session_id?: string;
        /**
         * Number of results to return.
         */
        limit?: number;
        /**
         * Number of results to skip. Used to move through results.
         */
        offset?: number;
        /**
         * String value that is logged to analytics denoting the trigger for the query.
         * Options include:
         * * `suggest`, sent if the query is triggered from a spelling correction.
         * * `initialize`, sent if the query is being triggered by a default initial search (in other words, the user did not enter query).
         *
         */
        queryTrigger?: string;
        /**
         * Context is an arbitrary JSON object that is passed to query rules to be used for triggering rules as well as passing data to those rules. This parameter should be provided as a URL-encoded string containing a JSON object.
         */
        context?: string;
        /**
         * The URL of the webpage that directed to the page this request was made from.
         */
        referrerPageUrl?: string;
        /**
         * If true the query will skip spell checking.
         */
        skipSpellCheck?: boolean;
        /**
         * This parameter represents one or more filtering conditions that are applied to the set of entities that would otherwise be returned. This parameter should be provided as a URL-encoded string containing a JSON object.
         *
         * For example, if the filter JSON is `{"name":{"$eq":"John"}}`, then the filters param after URL-encoding will be: `filters=%7B%22name%22%3A%7B%22%24eq%22%3A%22John%22%7D%7D`
         *
         * **Basic Filter Structure**
         *
         * The filter object at its core consists of a *matcher*, a *field*, and an *argument*.
         *
         * For example, in the following filter JSON:
         *
         * ```
         * {
         * "name":{
         * "$eq":"John"
         * }
         * }
         * ```
         *
         * `$eq` is the *matcher*, or filtering operation (equals, in this example),
         *
         * `name` is the *field* being filtered by, and
         *
         * `John` is *value* to be matched against.
         *
         * **Combining Multiple Filters**
         *
         * Multiple filters can be combined to form a conjunction (AND) of disjunctions (ORs) using the *combinators* `$and` and `$or`.  For example:
         * ```
         * {
         * "$and": [
         * {
         * "$or": [
         * {
         * "firstName": {
         * "$eq": "Jane"
         * }
         * },
         * {
         * "firstName": {
         * "$eq": "John"
         * }
         * }
         * ]
         * },
         * {
         * "lastName": {
         * "$eq": "Smith"
         * }
         * }
         * ]
         * }
         * ```
         * Any filter that is the only item in its respective combinator may omit the combinator as is done with the lastName above.
         *
         * **Filter Negation**
         *
         * Certain filter types may be negated. For example:
         *
         * ```
         * {
         * "$not": {
         * "name": {
         * "$eq": "John"
         * }
         * }
         * }
         * ```
         *
         * This can also be written more simply with a `!` in the `$eq` parameter. The following filter would have the same effect:
         *
         * ```
         * {
         * "name":{
         * "!$eq":"John"
         * }
         * }
         * ```
         *
         * **TEXT**
         *
         * The `TEXT` filter type is supported for text fields. (e.g., **`name`**, **`countryCode`**)
         *
         * <table style="width:100%">
         * <tr>
         * <th>Matcher</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>$eq (equals)</th>
         * <th>
         *
         * {
         * "countryCode":{
         * "$eq":"US"
         * }
         * },
         * {
         * "countryCode":{
         * "!$eq":"US"
         * }
         * }
         *
         * Supports negation. Case insensitive.
         * </tr>
         * <tr>
         * </table>
         *
         * **BOOLEAN**
         *
         *
         * The BOOLEAN filter type is supported for boolean fields and Yes / No custom fields.
         * <table style="width:100%">
         * <tr>
         * <th>Matcher</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>$eq</th>
         * <th>
         *
         * {
         * "isFreeEvent": {
         * "$eq": true
         * }
         * }
         *
         * For booleans, the filter takes a boolean value, not a string.
         * Supports negation.
         * </tr>
         * </table>
         *
         * **OPTION**
         *
         * The OPTION filter type is supported for option custom fields and fields that have a predetermined list of valid values.
         *
         * *e.g., **`eventStatus`**, **`gender`**, `SINGLE_OPTION` and `MULTI_OPTION` types of custom fields.*
         *
         * <table style="width:100%">
         * <tr>
         * <th>Matcher</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>$eq</th>
         * <th>
         *
         * Matching is case insensitive and insensitive to consecutive whitespace.
         *
         * e.g., "XYZ 123" matches "xyz       123"
         *
         * {
         * "eventStatus": {
         * "$eq": "SCHEDULED"
         * }
         * }
         * </table>
         *
         * **INTEGER, FLOAT, DATE, DATETIME, and TIME**
         *
         * These filter types are strictly ordered -- therefore, they support the following matchers:
         * - Equals
         * - Less Than / Less Than or Equal To
         * - Greater Than / Greater Than or Equal To
         *
         * <table style="width:100%">
         * <tr>
         * <th>Matcher</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>$eq</th>
         * <th>
         *
         * Equals
         *
         * {
         * "ageRange.maxValue": {
         * "$eq": "80"
         * }
         * }
         *
         * Supports negation.
         *
         * </tr>
         * <tr>
         * <th>$lt</th>
         * <th>
         *
         * Less than
         *
         * {
         * "time.start": {
         * "$lt": "2018-08-28T05:56"
         * }
         * }
         *
         * </tr>
         * <tr>
         * <th>$gt</th>
         * <th>
         *
         * Greater than
         *
         * {
         * "ageRange.maxValue": {
         * "$gt": "50"
         * }
         * }
         *
         * </tr>
         * <tr>
         * <th>$le</th>
         * <th>
         *
         * Less than or equal to
         *
         * {
         * "ageRange.maxValue": {
         * "$le": "40"
         * }
         * }
         *
         * </tr>
         * <tr>
         * <th>$ge</th>
         * <th>
         *
         * Greater than or equal to
         *
         * {
         * "time.end": {
         * "$ge":  "2018-08-28T05:56"
         * }
         * }
         *
         * </tr>
         * <tr>
         * <th>$between</th>
         * <th>
         *
         * An array that must contain exactly two elements with which the result is between.
         *
         * {
         * "time.end": {
         * "$between":  ["2018-08-28T05:56", "2018-08-29T05:56"]
         * }
         * }
         *
         * </tr>
         * <tr>
         * <th>Combinations</th>
         * <th>
         *
         * In addition to between, it is possible to combine multiple matchers for a result similar to an "and" operation:
         *
         * {
         * "ageRange.maxValue" : {
         * "$gt" : 10,
         * "$lt": 20
         * }
         * }
         *
         * </tr>
         * </table>
         *
         */
        filters?: string;
        /**
         * This parameter represents the state of the currently checked facet options. This parameter should be provided as a URL-encoded string containing a JSON object.
         *
         * The JSON object contains a key for each facet category that has a checked facet option.  The value for each of these keys is an array of Filter objects that describe the filter that is applied by the facet option.
         *
         * At the moment, facet options only support `$eq`.
         *
         * For example, if `Engineering` was checked under the `Category` facet and `Chicago` and `New York` are checked under the `Job Location` facet, the `facetFilters` would look like:
         * ```
         * {
         * "c_jobCategory": [
         * {
         * "c_jobCategory": {
         * "$eq": "Engineering"
         * }
         * }
         * ],
         * "c_jobLocation": [
         * {
         * "c_jobLocation": {
         * "$eq": "Chicago"
         * }
         * },
         * {
         * "c_jobLocation": {
         * "$eq": "New York"
         * }
         * }
         * ]
         * }
         * ```
         *
         */
        facetFilters?: string;
        /**
         * Whether facets should be computed for this vertical query.
         */
        retrieveFacets?: boolean;
        /**
         * This parameter overrides the sort options that are configured on the experience configuration.  This parameter should be provided as a URL-encoded string containing a JSON array.
         *
         * The input is a JSON array containing each of the sort options in the order in which they should be applied.
         *
         * Each sort options must contain a `type`
         *
         * <table style="width:100%">
         * <tr>
         * <th>Type</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>RELEVANCE</th>
         * <th>Sorts based on relevance according to the algorithm and, when relevant, location bias</th>
         * </tr>
         * <tr>
         * <th>ENTITY_DISTANCE</th>
         * <th>Sorts based on entity distance alone</th>
         * </tr>
         * <tr>
         * <th>FIELD</th>
         * <th>sorts based on a field with the direction specified</th>
         * </tr>
         * </table>
         *
         * </br>
         *
         * If the `type` is `FIELD` the sort options must also specify `field` which is the api name of the field to sort on.
         *
         * Finally, if the `type` is `FIELD` the sort options must also specify the `direction`.
         *
         * <table style="width:100%">
         * <tr>
         * <th>Direction</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>ASC</th>
         * <th>Sorts in ascending order.  For numbers this is low to high. For text this is alphabetical.  For dates this is chronological order.</th>
         * </tr>
         * <tr>
         * <th>DESC</th>
         * <th>Sorts in ascending order.  For numbers this is high to low. For text this is reverse alphabetical.  For dates this is reverse chronological order.</th>
         * </tr>
         * </table>
         *
         * </br>
         *
         * **Examples**
         * ```
         * [
         * {
         * "type": "FIELD",
         * "direction": "ASC",
         * "field": "startDate"
         * },
         * {
         * "type": "RELEVANCE",
         * "direction": "ASC"
         * }
         * ]
         * ```
         *
         */
        sortBys?: string;
        /**
         * When set to true, ignores any Query Rules that would otherwise affect the results. Defaults to false.
         */
        ignoreQueryRules?: boolean;
        /**
         * UUID of the query; recommended when moving through results, to associate multiple requests to the same query.
         */
        queryId?: string;
        /**
         * Indicates where the query is coming from (e.g. `"HOME_HEADER"` or `"TICKET_FORM"`). Can be used in Analytics reports via the `Integration Source` dimension. Defaults to `"STANDARD"`.
         */
        source?: string;
        /**
         * The version of the Search UI used for this request. Deprecated.
         */
        jsLibVersion?: string;
    };
    url: '/accounts/{accountId}/search/vertical/query';
};

export type VerticalQueryErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type VerticalQueryError = VerticalQueryErrors[keyof VerticalQueryErrors];

export type VerticalQueryResponses = {
    /**
     * VerticalQueryResponse
     *
     * Vertical Query Response
     */
    200: {
        meta?: ResponseMeta;
        response?: {
            businessId?: BusinessId;
            queryId?: QueryId;
            resultsCount?: ResultCount;
            results?: Results;
            appliedQueryFilters?: AppliedQueryFilters;
            /**
             * Contextual facets that contain metadata about the facet as well as the full facet.
             */
            facets?: Array<Facets>;
            searchIntents?: SearchIntents;
            /**
             * Identifier for the backend source of the response.
             */
            source?: string;
            directAnswer?: DirectAnswer;
            /**
             * Response information from running this query on other verticals.
             */
            alternativeVerticals?: {
                modules?: Modules;
                failedVerticals?: FailedVerticals;
            };
            spellCheck?: SpellCheck;
            locationBias?: LocationBias;
            /**
             * All results for this vertical.
             */
            allResultsForVertical?: {
                businessId?: BusinessId;
                queryId?: QueryId;
                resultsCount?: ResultCount;
                results?: Results;
                /**
                 * Contextual facets that contain metadata about the facet as well as the full facet.
                 */
                facets?: Array<Facets>;
                searchIntents?: SearchIntents;
            };
        };
    };
};

export type VerticalQueryResponse = VerticalQueryResponses[keyof VerticalQueryResponses];

export type FiltersearchData = {
    body?: never;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * String key that uniquely identifies the vertical to scope the filter search request to.
         */
        verticalKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`).
         */
        locale: string;
        /**
         * The search term of the user.
         */
        input: string;
        /**
         * This parameter represents the parameters that should be used for filter search. This parameter should be provided as a URL-encoded string containing a JSON object.
         *
         * Filter search uses the user's input string to find a set of existing filters that match the user's input query for the fields provided in the parameters.
         *
         * The JSON object must have a `fields` property made up of a list of `FilterField` objects that have the following properties:
         *
         * <table style="width:100%">
         * <tr>
         * <th>Property</th>
         * <th>Details</th>
         * </tr>
         * <tr>
         * <th>fieldId</th>
         * <th>The api name of the field.</th>
         * </tr>
         * <tr>
         * <th>entityTypeId</th>
         * <th>The api name for the entity type the filter belongs to.</th>
         * </tr>
         * <tr>
         * <th>shouldFetchEntities</th>
         * <th>Optional boolean.  If true, entities matching each filter will be returned inline with the filter.</th>
         * </tr>
         * </table>
         *
         * </br>
         *
         * Additionally, there is an optional boolean property `sectioned`.  If set to true, the matching filters will be returned in a separate section per field.  By default, they are all returned in the same section.
         *
         */
        search_parameters: string;
        /**
         * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
         */
        version?: string;
        /**
         * This parameter represents any values which should not be returned. This parameter should be provided as a URL-encoded string containing a JSON array, where each entry of the array is a JSON object representing a field and an excluded value for that field. For example:
         * ```
         * [
         * {
         * "name": {
         * "$eq": "John"
         * }
         * },
         * {
         * "c_jobCategory": {
         * "$eq": "Engineering"
         * }
         * }
         * ]
         * ```
         *
         */
        excluded?: string;
    };
    url: '/accounts/{accountId}/search/filtersearch';
};

export type FiltersearchErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type FiltersearchError = FiltersearchErrors[keyof FiltersearchErrors];

export type FiltersearchResponses = {
    /**
     * FilterSearchResponse
     *
     * Filter Search Response
     */
    200: {
        meta?: ResponseMeta;
        response?: {
            businessId?: BusinessId;
            /**
             * The set of field names being queried, and their respective results for the current query
             *
             */
            sections?: Array<{
                /**
                 * The display name of the field being queried, can be used in a UI to distinguish one section from another
                 *
                 */
                label?: string;
                /**
                 * The set of matches for the current query
                 *
                 */
                results?: Array<{
                    /**
                     * The API name of a field with a match for the current query
                     *
                     */
                    key?: string;
                    /**
                     * The display name of the field value with a match for the current query
                     *
                     */
                    value?: string;
                    filter?: Filter;
                    /**
                     * A set of offsets that represent the portion of the "value" that is a match for the current query
                     *
                     */
                    matchedSubstrings?: Array<{
                        /**
                         * In the "value", the number of characters between the beginning of the string and the start of the match for the current query
                         *
                         */
                        offset?: number;
                        /**
                         * In the "value", the number of characters from the offset that represents the end of the match for the current query
                         *
                         */
                        length?: number;
                    }>;
                    /**
                     * If a unique entity returns for the current query, the full entity object
                     *
                     */
                    relatedItem?: {
                        [key: string]: unknown;
                    };
                }>;
            }>;
            failedVerticals?: FailedVerticals;
            queryId?: QueryId;
        };
    };
};

export type FiltersearchResponse = FiltersearchResponses[keyof FiltersearchResponses];

export type GenerateAnswerData = {
    /**
     * JSON object containing the search results and user query to generate an answer.
     */
    body: GenerateAnswerRequest;
    path: {
        accountId: string;
    };
    query: {
        /**
         * A date in `YYYYMMDD` format.
         */
        v: string;
        /**
         * String key that uniquely identifies the Search experience.
         */
        experienceKey: string;
        /**
         * The locale code of the experience (e.g. `en_GB`). Only returns entities that have an entity profile associated with this locale.
         */
        locale: string;
    };
    url: '/accounts/{accountId}/search/generateAnswer';
};

export type GenerateAnswerErrors = {
    /**
     * ErrorResponse
     *
     * Error Response
     */
    400: {
        meta?: ResponseMetaWithError;
        response?: {
            [key: string]: unknown;
        };
    };
};

export type GenerateAnswerError = GenerateAnswerErrors[keyof GenerateAnswerErrors];

export type GenerateAnswerResponses = {
    /**
     * GenerateAnswerResponse
     *
     * Generate Answer Response
     */
    200: {
        meta?: ResponseMeta;
        response?: {
            /**
             * The direct answer for the query.
             */
            directAnswer?: string;
            /**
             * The status of the result.
             */
            resultStatus?: string;
            /**
             * The list of entity IDs that were used to generate the answer.
             */
            citations?: Array<string>;
        };
    };
};

export type GenerateAnswerResponse = GenerateAnswerResponses[keyof GenerateAnswerResponses];
