// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zResponseMeta = z.object({
    uuid: z.string().optional()
});

export const zResponseError = z.object({
    name: z.string().optional(),
    code: z.int().optional(),
    type: z.enum([
        'FATAL_ERROR',
        'NON_FATAL_ERROR',
        'WARNING'
    ]).optional(),
    message: z.string().optional()
});

export const zResponseMetaWithError = zResponseMeta.and(z.object({
    errors: z.array(zResponseError).optional()
}));

/**
 * ID of the account associated with this Search experience
 */
export const zBusinessId = z.int();

/**
 * UUID for the query
 */
export const zQueryId = z.string();

/**
 * String key that uniquely identifies the vertical.
 */
export const zVerticalConfigId = z.string();

/**
 * The number of entities within the vertical that are relevant to the user's query.
 *
 */
export const zResultCount = z.int();

export const zEntity = z.object({
    data: z.record(z.string(), z.unknown()).optional(),
    highlightedFields: z.record(z.string(), z.unknown()).optional(),
    distance: z.int().optional(),
    distanceFromFilter: z.int().optional()
});

/**
 * The individual entity results that contain metadata about the entity as well as the fully rendered profiles.
 *
 */
export const zResults = z.array(zEntity);

/**
 * The filter, in the filter format, that was applied.
 * <br><br>
 * For example: `"c_exampleFieldId": { $eq": "Search" }`
 *
 */
export const zFilter = z.record(z.string(), z.unknown());

/**
 * A list of the filters that were inferred from the user's query and applied at search time.
 */
export const zAppliedQueryFilters = z.array(z.object({
    displayKey: z.string().optional(),
    displayValue: z.string().optional(),
    filter: zFilter.optional(),
    type: z.enum([
        'FIELD_VALUE',
        'PLACE',
        'INTENT'
    ]).optional(),
    details: z.record(z.string(), z.unknown()).optional()
}));

/**
 * The results and metadata pertaining to a single vertical relevant to the user's query.
 */
export const zModule = z.object({
    verticalConfigId: zVerticalConfigId.optional(),
    resultCount: zResultCount.optional(),
    encodedState: z.string().optional(),
    results: zResults.optional(),
    appliedQueryFilters: zAppliedQueryFilters.optional()
});

/**
 * List of results for each vertical that was relevant to the query, returned in the order of relevance.
 */
export const zModules = z.array(zModule);

export const zFailedVertical = z.object({
    verticalConfigId: zVerticalConfigId.optional(),
    errorType: z.enum([
        'TIMEOUT',
        'BACKEND_ERROR',
        'INVALID_CONFIG',
        'INVALID_QUERY'
    ]).optional(),
    details: z.object({
        responseCode: z.int().optional(),
        description: z.string().optional()
    }).optional(),
    queryDurationMillis: z.int().optional()
});

/**
 * Contains error information when one or more verticals fail to return results.
 *
 */
export const zFailedVerticals = z.array(zFailedVertical);

/**
 * Information that is estimated to directly answer the question of the query.
 *
 */
export const zDirectAnswer = z.object({
    type: z.string().optional(),
    answer: z.record(z.string(), z.unknown()).optional(),
    relatedItem: z.object({
        verticalConfigId: zVerticalConfigId.optional(),
        data: z.record(z.string(), z.unknown()).optional()
    }).optional()
});

/**
 * Highlighting instructions for a field value, containing the original value of the field and all sections of the value that should be highlighted.
 *
 */
export const zHighlightedValue = z.object({
    value: z.string().optional(),
    matchedSubstrings: z.array(z.object({
        offsets: z.int().optional(),
        length: z.int().optional()
    })).optional()
});

/**
 * SpellCheck information that may correct the user's query.
 */
export const zSpellCheck = z.object({
    originalQuery: z.string().optional(),
    correctedQuery: zHighlightedValue.optional(),
    type: z.enum([
        'SUGGEST',
        'AUTOCORRECT',
        'COMBINE'
    ]).optional()
});

/**
 * Information about geographical location biases used in the search.
 */
export const zLocationBias = z.object({
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    locationDisplayName: z.string().optional(),
    accuracy: z.enum([
        'IP',
        'DEVICE',
        'UNKNOWN'
    ]).optional()
});

export const zFacets = z.object({
    fieldId: z.string().optional(),
    displayName: z.string().optional(),
    options: z.array(z.object({
        displayName: z.string().optional(),
        count: z.int().optional(),
        isSelected: z.boolean().optional(),
        filter: zFilter.optional()
    })).optional()
});

/**
 * Items in array each represent a particular intent expressed in the user's query. Example: `NEAR_ME`
 *
 */
export const zSearchIntents = z.array(z.string());

export const zGenerateAnswerRequest = z.object({
    searchId: z.string(),
    searchTerm: z.string(),
    results: z.union([
        zModule,
        z.object({
            verticals: zModules.optional()
        })
    ])
});

export const zAccountId = z.string();

/**
 * A date in `YYYYMMDD` format.
 */
export const zV = z.string();

/**
 * String key that uniquely identifies the Search experience.
 */
export const zExperienceKey = z.string();

/**
 * The locale code of the experience (e.g. `en_GB`).
 */
export const zLocale = z.string();

/**
 * The partial search term from the user.
 */
export const zAutocompleteInput = z.string();

/**
 * Number of autocomplete results to return.
 */
export const zAutocompleteLimit = z.int().gte(1).lte(100).default(10);

/**
 * The label or version number of the experience configuration to use. Label options are `STAGING` or `PRODUCTION`. `STAGING` uses the Latest version of the configuration. If omitted the `PRODUCTION` label will be used.
 */
export const zVersion = z.string();

/**
 * The locale code of the experience (e.g. `en_GB`). Only returns entities that have an entity profile associated with this locale.
 */
export const zQueryLocale = z.string();

/**
 * The search term of the user.
 */
export const zRequiredInput = z.string();

/**
 * The user's location as a comma separated latitude and longitude (e.g. `"40.740957,-73.987565"`).
 */
export const zLocation = z.string();

/**
 * UUID used to track session state when cookies are blocked.
 */
export const zSessionId = z.string();

/**
 * JSON object specifying the limit for each vertical.  Each key is a vertical key and the value for each of those keys is a number 1-50 that denotes the limit for that vertical. This parameter should be provided as a URL-encoded string containing a JSON object.
 */
export const zUniversalLimit = z.string();

/**
 * String value that is logged to analytics denoting the trigger for the query.
 * Options include:
 * * `suggest`, sent if the query is triggered from a spelling correction.
 * * `initialize`, sent if the query is being triggered by a default initial search (in other words, the user did not enter query).
 *
 */
export const zQueryTrigger = z.string();

/**
 * Context is an arbitrary JSON object that is passed to query rules to be used for triggering rules as well as passing data to those rules. This parameter should be provided as a URL-encoded string containing a JSON object.
 */
export const zContext = z.string();

/**
 * The URL of the webpage that directed to the page this request was made from.
 */
export const zReferrerPageUrl = z.string();

/**
 * If true the query will skip spell checking.
 */
export const zSkipSpellCheck = z.boolean();

/**
 * A comma-separated list of verticals (e.g. `"people,locations"`). If specified, only results from these verticals will be returned.
 */
export const zRestrictVerticals = z.string();

/**
 * When set to true, ignores any Query Rules that would otherwise affect the results. Defaults to false.
 */
export const zIgnoreQueryRules = z.boolean();

/**
 * UUID of the query; recommended when moving through results, to associate multiple requests to the same query.
 */
export const zQueryId2 = z.string();

/**
 * Indicates where the query is coming from (e.g. `"HOME_HEADER"` or `"TICKET_FORM"`). Can be used in Analytics reports via the `Integration Source` dimension. Defaults to `"STANDARD"`.
 */
export const zSource = z.string();

/**
 * The version of the Search UI used for this request. Deprecated.
 */
export const zJsLibVersion = z.string();

/**
 * String key that uniquely identifies the vertical.
 */
export const zVerticalKey = z.string();

/**
 * The search term of the user.
 */
export const zVerticalInput = z.string();

/**
 * Radius (in meters) that should be applied to any location filter that does not already have an explicit radius.
 */
export const zLocationRadius = z.string();

/**
 * Number of results to return.
 */
export const zLimit = z.int().lte(50).default(10);

/**
 * Number of results to skip. Used to move through results.
 */
export const zOffset = z.int().gte(0).lte(9949).default(0);

/**
 * This parameter represents one or more filtering conditions that are applied to the set of entities that would otherwise be returned. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * For example, if the filter JSON is `{"name":{"$eq":"John"}}`, then the filters param after URL-encoding will be: `filters=%7B%22name%22%3A%7B%22%24eq%22%3A%22John%22%7D%7D`
 *
 * **Basic Filter Structure**
 *
 * The filter object at its core consists of a *matcher*, a *field*, and an *argument*.
 *
 * For example, in the following filter JSON:
 *
 * ```
 * {
 * "name":{
 * "$eq":"John"
 * }
 * }
 * ```
 *
 * `$eq` is the *matcher*, or filtering operation (equals, in this example),
 *
 * `name` is the *field* being filtered by, and
 *
 * `John` is *value* to be matched against.
 *
 * **Combining Multiple Filters**
 *
 * Multiple filters can be combined to form a conjunction (AND) of disjunctions (ORs) using the *combinators* `$and` and `$or`.  For example:
 * ```
 * {
 * "$and": [
 * {
 * "$or": [
 * {
 * "firstName": {
 * "$eq": "Jane"
 * }
 * },
 * {
 * "firstName": {
 * "$eq": "John"
 * }
 * }
 * ]
 * },
 * {
 * "lastName": {
 * "$eq": "Smith"
 * }
 * }
 * ]
 * }
 * ```
 * Any filter that is the only item in its respective combinator may omit the combinator as is done with the lastName above.
 *
 * **Filter Negation**
 *
 * Certain filter types may be negated. For example:
 *
 * ```
 * {
 * "$not": {
 * "name": {
 * "$eq": "John"
 * }
 * }
 * }
 * ```
 *
 * This can also be written more simply with a `!` in the `$eq` parameter. The following filter would have the same effect:
 *
 * ```
 * {
 * "name":{
 * "!$eq":"John"
 * }
 * }
 * ```
 *
 * **TEXT**
 *
 * The `TEXT` filter type is supported for text fields. (e.g., **`name`**, **`countryCode`**)
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq (equals)</th>
 * <th>
 *
 * {
 * "countryCode":{
 * "$eq":"US"
 * }
 * },
 * {
 * "countryCode":{
 * "!$eq":"US"
 * }
 * }
 *
 * Supports negation. Case insensitive.
 * </tr>
 * <tr>
 * </table>
 *
 * **BOOLEAN**
 *
 *
 * The BOOLEAN filter type is supported for boolean fields and Yes / No custom fields.
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * {
 * "isFreeEvent": {
 * "$eq": true
 * }
 * }
 *
 * For booleans, the filter takes a boolean value, not a string.
 * Supports negation.
 * </tr>
 * </table>
 *
 * **OPTION**
 *
 * The OPTION filter type is supported for option custom fields and fields that have a predetermined list of valid values.
 *
 * *e.g., **`eventStatus`**, **`gender`**, `SINGLE_OPTION` and `MULTI_OPTION` types of custom fields.*
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * Matching is case insensitive and insensitive to consecutive whitespace.
 *
 * e.g., "XYZ 123" matches "xyz       123"
 *
 * {
 * "eventStatus": {
 * "$eq": "SCHEDULED"
 * }
 * }
 * </table>
 *
 * **INTEGER, FLOAT, DATE, DATETIME, and TIME**
 *
 * These filter types are strictly ordered -- therefore, they support the following matchers:
 * - Equals
 * - Less Than / Less Than or Equal To
 * - Greater Than / Greater Than or Equal To
 *
 * <table style="width:100%">
 * <tr>
 * <th>Matcher</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>$eq</th>
 * <th>
 *
 * Equals
 *
 * {
 * "ageRange.maxValue": {
 * "$eq": "80"
 * }
 * }
 *
 * Supports negation.
 *
 * </tr>
 * <tr>
 * <th>$lt</th>
 * <th>
 *
 * Less than
 *
 * {
 * "time.start": {
 * "$lt": "2018-08-28T05:56"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$gt</th>
 * <th>
 *
 * Greater than
 *
 * {
 * "ageRange.maxValue": {
 * "$gt": "50"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$le</th>
 * <th>
 *
 * Less than or equal to
 *
 * {
 * "ageRange.maxValue": {
 * "$le": "40"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$ge</th>
 * <th>
 *
 * Greater than or equal to
 *
 * {
 * "time.end": {
 * "$ge":  "2018-08-28T05:56"
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>$between</th>
 * <th>
 *
 * An array that must contain exactly two elements with which the result is between.
 *
 * {
 * "time.end": {
 * "$between":  ["2018-08-28T05:56", "2018-08-29T05:56"]
 * }
 * }
 *
 * </tr>
 * <tr>
 * <th>Combinations</th>
 * <th>
 *
 * In addition to between, it is possible to combine multiple matchers for a result similar to an "and" operation:
 *
 * {
 * "ageRange.maxValue" : {
 * "$gt" : 10,
 * "$lt": 20
 * }
 * }
 *
 * </tr>
 * </table>
 *
 */
export const zFilters = z.string();

/**
 * This parameter represents the state of the currently checked facet options. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * The JSON object contains a key for each facet category that has a checked facet option.  The value for each of these keys is an array of Filter objects that describe the filter that is applied by the facet option.
 *
 * At the moment, facet options only support `$eq`.
 *
 * For example, if `Engineering` was checked under the `Category` facet and `Chicago` and `New York` are checked under the `Job Location` facet, the `facetFilters` would look like:
 * ```
 * {
 * "c_jobCategory": [
 * {
 * "c_jobCategory": {
 * "$eq": "Engineering"
 * }
 * }
 * ],
 * "c_jobLocation": [
 * {
 * "c_jobLocation": {
 * "$eq": "Chicago"
 * }
 * },
 * {
 * "c_jobLocation": {
 * "$eq": "New York"
 * }
 * }
 * ]
 * }
 * ```
 *
 */
export const zFacetFilters = z.string();

/**
 * Whether facets should be computed for this vertical query.
 */
export const zRetrieveFacets = z.boolean();

/**
 * This parameter overrides the sort options that are configured on the experience configuration.  This parameter should be provided as a URL-encoded string containing a JSON array.
 *
 * The input is a JSON array containing each of the sort options in the order in which they should be applied.
 *
 * Each sort options must contain a `type`
 *
 * <table style="width:100%">
 * <tr>
 * <th>Type</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>RELEVANCE</th>
 * <th>Sorts based on relevance according to the algorithm and, when relevant, location bias</th>
 * </tr>
 * <tr>
 * <th>ENTITY_DISTANCE</th>
 * <th>Sorts based on entity distance alone</th>
 * </tr>
 * <tr>
 * <th>FIELD</th>
 * <th>sorts based on a field with the direction specified</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * If the `type` is `FIELD` the sort options must also specify `field` which is the api name of the field to sort on.
 *
 * Finally, if the `type` is `FIELD` the sort options must also specify the `direction`.
 *
 * <table style="width:100%">
 * <tr>
 * <th>Direction</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>ASC</th>
 * <th>Sorts in ascending order.  For numbers this is low to high. For text this is alphabetical.  For dates this is chronological order.</th>
 * </tr>
 * <tr>
 * <th>DESC</th>
 * <th>Sorts in ascending order.  For numbers this is high to low. For text this is reverse alphabetical.  For dates this is reverse chronological order.</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * **Examples**
 * ```
 * [
 * {
 * "type": "FIELD",
 * "direction": "ASC",
 * "field": "startDate"
 * },
 * {
 * "type": "RELEVANCE",
 * "direction": "ASC"
 * }
 * ]
 * ```
 *
 */
export const zSortBys = z.string();

/**
 * String key that uniquely identifies the vertical to scope the filter search request to.
 */
export const zFilterSearchVerticalKey = z.string();

/**
 * This parameter represents the parameters that should be used for filter search. This parameter should be provided as a URL-encoded string containing a JSON object.
 *
 * Filter search uses the user's input string to find a set of existing filters that match the user's input query for the fields provided in the parameters.
 *
 * The JSON object must have a `fields` property made up of a list of `FilterField` objects that have the following properties:
 *
 * <table style="width:100%">
 * <tr>
 * <th>Property</th>
 * <th>Details</th>
 * </tr>
 * <tr>
 * <th>fieldId</th>
 * <th>The api name of the field.</th>
 * </tr>
 * <tr>
 * <th>entityTypeId</th>
 * <th>The api name for the entity type the filter belongs to.</th>
 * </tr>
 * <tr>
 * <th>shouldFetchEntities</th>
 * <th>Optional boolean.  If true, entities matching each filter will be returned inline with the filter.</th>
 * </tr>
 * </table>
 *
 * </br>
 *
 * Additionally, there is an optional boolean property `sectioned`.  If set to true, the matching filters will be returned in a separate section per field.  By default, they are all returned in the same section.
 *
 */
export const zSearchParameters = z.string();

/**
 * This parameter represents any values which should not be returned. This parameter should be provided as a URL-encoded string containing a JSON array, where each entry of the array is a JSON object representing a field and an excluded value for that field. For example:
 * ```
 * [
 * {
 * "name": {
 * "$eq": "John"
 * }
 * },
 * {
 * "c_jobCategory": {
 * "$eq": "Engineering"
 * }
 * }
 * ]
 * ```
 *
 */
export const zExcluded = z.string();

export const zAutocompletePath = z.object({
    accountId: z.string()
});

export const zAutocompleteQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    locale: z.string(),
    input: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(10),
    version: z.string().optional()
});

/**
 * AutocompleteResponse
 *
 * Autocomplete Request Response
 */
export const zAutocompleteResponse = z.object({
    input: z.object({
        value: z.string().optional(),
        queryIntents: z.array(z.string()).optional()
    }).optional(),
    results: z.array(z.object({
        value: z.string().optional(),
        matchedSubstrings: z.array(z.object({
            offsets: z.int().optional(),
            length: z.int().optional()
        })).optional(),
        queryIntents: z.array(z.string()).optional(),
        verticalKeys: z.array(z.string()).optional()
    })).optional()
});

export const zQueryPath = z.object({
    accountId: z.string()
});

export const zQueryQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    locale: z.string(),
    input: z.string(),
    version: z.string().optional(),
    location: z.string().optional(),
    session_id: z.string().optional(),
    limit: z.string().optional(),
    queryTrigger: z.string().optional(),
    context: z.string().optional(),
    referrerPageUrl: z.string().optional(),
    skipSpellCheck: z.boolean().optional(),
    restrictVerticals: z.string().optional(),
    ignoreQueryRules: z.boolean().optional(),
    queryId: z.string().optional(),
    source: z.string().optional(),
    jsLibVersion: z.string().optional()
});

/**
 * UniversalQueryResponse
 *
 * Universal Query Response
 */
export const zQueryResponse = z.object({
    meta: zResponseMeta.optional(),
    response: z.object({
        businessId: zBusinessId.optional(),
        queryId: zQueryId.optional(),
        modules: zModules.optional(),
        failedVerticals: zFailedVerticals.optional(),
        directAnswer: zDirectAnswer.optional(),
        spellCheck: zSpellCheck.optional(),
        locationBias: zLocationBias.optional()
    }).optional()
});

export const zVerticalAutocompletePath = z.object({
    accountId: z.string()
});

export const zVerticalAutocompleteQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    verticalKey: z.string(),
    locale: z.string(),
    input: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(10),
    version: z.string().optional()
});

/**
 * AutocompleteResponse
 *
 * Autocomplete Request Response
 */
export const zVerticalAutocompleteResponse = z.object({
    input: z.object({
        value: z.string().optional(),
        queryIntents: z.array(z.string()).optional()
    }).optional(),
    results: z.array(z.object({
        value: z.string().optional(),
        matchedSubstrings: z.array(z.object({
            offsets: z.int().optional(),
            length: z.int().optional()
        })).optional(),
        queryIntents: z.array(z.string()).optional(),
        verticalKeys: z.array(z.string()).optional()
    })).optional()
});

export const zVerticalQueryPath = z.object({
    accountId: z.string()
});

export const zVerticalQueryQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    verticalKey: z.string(),
    locale: z.string(),
    input: z.string().optional(),
    version: z.string().optional(),
    location: z.string().optional(),
    locationRadius: z.string().optional(),
    session_id: z.string().optional(),
    limit: z.int().lte(50).optional().default(10),
    offset: z.int().gte(0).lte(9949).optional().default(0),
    queryTrigger: z.string().optional(),
    context: z.string().optional(),
    referrerPageUrl: z.string().optional(),
    skipSpellCheck: z.boolean().optional(),
    filters: z.string().optional(),
    facetFilters: z.string().optional(),
    retrieveFacets: z.boolean().optional(),
    sortBys: z.string().optional(),
    ignoreQueryRules: z.boolean().optional(),
    queryId: z.string().optional(),
    source: z.string().optional(),
    jsLibVersion: z.string().optional()
});

/**
 * VerticalQueryResponse
 *
 * Vertical Query Response
 */
export const zVerticalQueryResponse = z.object({
    meta: zResponseMeta.optional(),
    response: z.object({
        businessId: zBusinessId.optional(),
        queryId: zQueryId.optional(),
        resultsCount: zResultCount.optional(),
        results: zResults.optional(),
        appliedQueryFilters: zAppliedQueryFilters.optional(),
        facets: z.array(zFacets).optional(),
        searchIntents: zSearchIntents.optional(),
        source: z.string().optional(),
        directAnswer: zDirectAnswer.optional(),
        alternativeVerticals: z.object({
            modules: zModules.optional(),
            failedVerticals: zFailedVerticals.optional()
        }).optional(),
        spellCheck: zSpellCheck.optional(),
        locationBias: zLocationBias.optional(),
        allResultsForVertical: z.object({
            businessId: zBusinessId.optional(),
            queryId: zQueryId.optional(),
            resultsCount: zResultCount.optional(),
            results: zResults.optional(),
            facets: z.array(zFacets).optional(),
            searchIntents: zSearchIntents.optional()
        }).optional()
    }).optional()
});

export const zFiltersearchPath = z.object({
    accountId: z.string()
});

export const zFiltersearchQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    verticalKey: z.string(),
    locale: z.string(),
    input: z.string(),
    search_parameters: z.string(),
    version: z.string().optional(),
    excluded: z.string().optional()
});

/**
 * FilterSearchResponse
 *
 * Filter Search Response
 */
export const zFiltersearchResponse = z.object({
    meta: zResponseMeta.optional(),
    response: z.object({
        businessId: zBusinessId.optional(),
        sections: z.array(z.object({
            label: z.string().optional(),
            results: z.array(z.object({
                key: z.string().optional(),
                value: z.string().optional(),
                filter: zFilter.optional(),
                matchedSubstrings: z.array(z.object({
                    offset: z.int().optional(),
                    length: z.int().optional()
                })).optional(),
                relatedItem: z.record(z.string(), z.unknown()).optional()
            })).optional()
        })).optional(),
        failedVerticals: zFailedVerticals.optional(),
        queryId: zQueryId.optional()
    }).optional()
});

/**
 * JSON object containing the search results and user query to generate an answer.
 */
export const zGenerateAnswerBody = zGenerateAnswerRequest;

export const zGenerateAnswerPath = z.object({
    accountId: z.string()
});

export const zGenerateAnswerQuery = z.object({
    v: z.string(),
    experienceKey: z.string(),
    locale: z.string()
});

/**
 * GenerateAnswerResponse
 *
 * Generate Answer Response
 */
export const zGenerateAnswerResponse = z.object({
    meta: zResponseMeta.optional(),
    response: z.object({
        directAnswer: z.string().optional(),
        resultStatus: z.string().optional(),
        citations: z.array(z.string()).optional()
    }).optional()
});
