// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { SendEventsData, SendEventsErrors, SendEventsResponses } from './types.gen.js';
import { zSendEventsResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Analytics Events
 *
 * Send user events from your Yext digital experiences to Yext Analytics in near real-time.
 *
 * This documentation is for version `1.0.0` of the Events API. If you are still using version
 * `0.6`, refer to the documentation in the yext/analytics Github repository
 * [here](https://github.com/yext/analytics/blob/release/v0.6.8/src/models/EventPayload.ts).
 *
 */
export const sendEvents = <ThrowOnError extends boolean = false>(options: Options<SendEventsData, ThrowOnError>): RequestResult<SendEventsResponses, SendEventsErrors, ThrowOnError> => (options.client ?? client).post<SendEventsResponses, SendEventsErrors, ThrowOnError>({
    responseValidator: async (data) => await zSendEventsResponse.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/accounts/me/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
