// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://us.yextevents.com' | 'https://aws.us.yextevents.com' | 'https://eu.yextevents.com' | 'https://gcp.eu.yextevents.com' | (string & {});
};

/**
 * Analytics Event
 *
 * Represents an event for analytics purposes.
 */
export type SendEventsRequestBody = {
    /**
     * The action which caused the event.
     */
    action: 'ADD_TO_CART' | 'ALL_TAB_NAVIGATION' | 'APPLY' | 'AUTO_COMPLETE_SELECTION' | 'BACKWARD_PAGINATE' | 'BOOK' | 'BRAND_ICON' | 'CASE_START' | 'CASE_SUBMITTED' | 'CHAT_IMPRESSION' | 'CHAT_LINK_CLICK' | 'CHAT_RESPONSE' | 'COLLAPSE' | 'CTA_CLICK' | 'DRIVING_DIRECTIONS' | 'EVENT' | 'EXPAND' | 'FEATURED_MESSAGE' | 'FILTERING_WITHIN_SECTION' | 'FORWARD_PAGINATE' | 'HEADER_LINKS' | 'ITEM_IN_LIST' | 'MAP_CARD' | 'MAP_PIN' | 'MENU' | 'MESSAGE' | 'ORDER' | 'PAGE_VIEW' | 'PAGINATE' | 'POST' | 'PRESET_PROMPT' | 'PRODUCT' | 'PROFILE' | 'QUESTION_FOCUS' | 'QUESTION_SUBMIT' | 'REMOVED_FILTER' | 'REVIEW' | 'SCROLL_TO_BOTTOM_OF_PAGE' | 'SEARCH_BAR_IMPRESSION' | 'SEARCH_CLEAR_BUTTON' | 'TAP_TO_CALL' | 'THUMBS_DOWN' | 'THUMBS_UP' | 'TICKET_URL' | 'TITLE' | 'VERTICAL_TAB_NAVIGATION' | 'VERTICAL_VIEW_ALL' | 'VOICE_START' | 'VOICE_STOP' | 'WEBSITE' | string;
    /**
     * An alternative to using the Authorization HTTP header. If a value is provided, it will override any Authorization header. Api keys should be formatted like "KEY \<apiKey\>", access tokens should be formatted like "Bearer \<bearerToken\>"
     */
    authorization?: string;
    /**
     * Whether the event is the result of bot activity.
     */
    bot?: boolean | '$auto';
    /**
     * Information about the visitor's device and browser.
     */
    browserAgent?: {
        /**
         * The browser associated with the event.
         */
        browser?: string | '$auto' | unknown;
        /**
         * The browser version associated with the event.
         */
        browserVersion?: string | '$auto' | unknown;
        /**
         * The device associated with the event.
         */
        device?: string | '$auto' | unknown;
        /**
         * The class of device associated with the event.
         */
        deviceClass?: string | '$auto' | unknown;
        /**
         * The operating system associated with the event.
         */
        os?: string | '$auto' | unknown;
        /**
         * The operating system version associated with the event.
         */
        osVersion?: string | '$auto' | unknown;
        /**
         * The user agent string for the event.
         */
        userAgent?: string | '$auto' | unknown;
    };
    /**
     * Chat
     *
     * The Yext Chat properties of the event.
     */
    chat?: {
        /**
         * The ID of the chat bot an event was tied to.
         */
        botId: string;
        /**
         * The ID of a conversation an event was tied to. Not all events are tied to a specific conversation. For example, both impressions are registered before the conversation begins. Must be 48 chars long
         */
        conversationId?: string;
        /**
         * The ID of the response an event was tied to. Not all events are tied to a specific response, but if present it must be a valid ULID. This is analogous to queryId in Search. `pattern: "^[0-9A-HJKMNP-TV-Z]{26}$"`
         */
        responseId?: string;
    };
    /**
     * Client SDK
     *
     * For the Yext client SDKs involved in the event, this is an object mapping the names of those SDKs to the version labels of those SDKs.
     */
    clientSdk?: {
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$'?: string;
    };
    /**
     * When one record summarizes multiple events, this is the number of events the record represents. The event is treated as if it is duplicated this many times.
     */
    count?: number;
    /**
     * Up to 10 pairs matching custom string keys to string values to associate with the event. Keys are case-insensitive; values are case-sensitive. Property Name `pattern: "^[a-zA-Z][a-zA-Z0-9_]{0,31}$"`
     */
    customTags?: {
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$'?: string;
    };
    /**
     * Up to 10 pairs matching custom string keys to number values to associate with the event. Keys are case-insensitive. Property Name `pattern: "^[a-zA-Z][a-zA-Z0-9_]{0,31}$"`
     */
    customValues?: {
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$'?: number;
    };
    /**
     * URL
     *
     * The URL of the page the event is directing the visitor to. `format: uri`
     */
    destinationUrl?: string;
    entity?: string | number;
    /**
     * Indicates whether the event is the result of internal activity.
     */
    internalUser?: boolean;
    /**
     * The IP address for the event.
     */
    ip?: {
        address: string | '$auto';
        /**
         * The algorithm to use to anonymize the IP address after collection.
         */
        algorithm: 'HASH';
    } | unknown;
    /**
     * A label assigned to the event, e.g. a CTA label.
     */
    label?: string;
    /**
     * The locale of the user who generated the event.
     */
    locale?: string | '$auto' | unknown;
    /**
     * The location information of the visitor for the event. Either a Coordinates object with both latitude and longitude or a string with the country of the visitor for the event, as a ISO 3166-1 alpha-2 country code.
     */
    location?: {
        /**
         * The geographic coordinates of the visitor for the event.
         */
        coordinates: {
            /**
             * The latitude, in degrees North.
             */
            latitude: number;
            /**
             * The longitude, in degrees East.
             */
            longitude: number;
        };
    } | string;
    /**
     * Pages
     *
     * Fields specific to reporting Yext Pages Analytics Events
     */
    pages?: {
        /**
         * The scope of an action. Applies to Pages events.
         */
        scope?: string;
        /**
         * The Event name as it was used in previous analytics implementations.
         */
        originalEventName?: string;
        /**
         * The UID of the site an event was tied to.
         */
        siteUid?: number;
        /**
         * The ID of the template from which a site was generated.
         */
        template?: string;
    };
    /**
     * The URL of the page the event occurred on.
     */
    pageUrl?: string | string | unknown;
    /**
     * The URL of the page which the visitor came from prior to the event.
     */
    referrerUrl?: string | unknown;
    /**
     * Search
     *
     * Fields specific to reporting Yext Search Analytics Events
     */
    search?: {
        /**
         * Unique identifier of the search
         */
        searchId?: string;
        /**
         * Unique identifier for a single query across pagination
         */
        queryId?: string;
        /**
         * The vertical key on which the event occurred, if any
         */
        verticalKey?: string;
        /**
         * Whether or not the event occurred on a direct answer card
         */
        isDirectAnswer?: boolean;
        /**
         * The label of the version number of the search config. Either "PRODUCTION" or "STAGING"
         */
        versionLabel?: 'PRODUCTION' | 'STAGING';
        /**
         * The version number of the search config
         */
        versionNumber?: number;
        /**
         * The identifier of the search experience.
         */
        experienceKey: string;
        /**
         * Whether or not the event occurred on a generative direct answer card
         */
        isGenerativeDirectAnswer?: boolean;
    };
    /**
     * The query entered by the user.
     */
    searchTerm?: string;
    /**
     * ID of the user session associated with event. `pattern: "^[\x20-\x7E]{1,36}$"`
     */
    sessionId?: string | unknown;
    /**
     * The timestamp at which the event occurred.
     */
    timestamp?: string | number | '$auto';
    /**
     * Value
     *
     * The monetary value of the event
     */
    value?: {
        /**
         * The monetary value of the event.
         */
        amount: number;
        /**
         * The ISO 4217 currency code of the currency the value is expressed in. `pattern: "^[A-Z]{3}$"`
         */
        currency: string;
    };
    /**
     * The visitor related to the event. Keys are visitor methods and values are visitor IDs. PropertyName pattern: "^[a-zA-Z0-9_-]{1,16}$". Value pattern: "^[\x20-\x7E]{1,64}$"
     */
    visitor?: {
        '^[a-zA-Z0-9_-]{1,16}$'?: string;
    };
};

export type SendEventsData = {
    /**
     * JSON object containing the events to be sent to Yext Analytics
     */
    body: SendEventsRequestBody;
    path?: never;
    query?: never;
    url: '/accounts/me/events';
};

export type SendEventsErrors = {
    /**
     * SendEventsResponse
     *
     * Exceeded the limit of requests in the last minute
     */
    429: {
        /**
         * The ID of the event.
         */
        id?: string;
        /**
         * Array of error messages that occurred during the request.
         */
        errors?: Array<unknown>;
    };
    /**
     * SendEventsResponse
     *
     * Error response
     */
    default: {
        /**
         * The ID of the event.
         */
        id?: string;
        /**
         * Array of error messages that occurred during the request.
         */
        errors?: Array<unknown>;
    };
};

export type SendEventsError = SendEventsErrors[keyof SendEventsErrors];

export type SendEventsResponses = {
    /**
     * SendEventsResponse
     *
     * Successful request, return analytics event ID that related to this event
     */
    202: {
        /**
         * The ID of the event.
         */
        id?: string;
    };
};

export type SendEventsResponse = SendEventsResponses[keyof SendEventsResponses];
