// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Analytics Event
 *
 * Represents an event for analytics purposes.
 */
export const zSendEventsRequestBody = z.object({
    action: z.union([
        z.literal('ADD_TO_CART'),
        z.literal('ALL_TAB_NAVIGATION'),
        z.literal('APPLY'),
        z.literal('AUTO_COMPLETE_SELECTION'),
        z.literal('BACKWARD_PAGINATE'),
        z.literal('BOOK'),
        z.literal('BRAND_ICON'),
        z.literal('CASE_START'),
        z.literal('CASE_SUBMITTED'),
        z.literal('CHAT_IMPRESSION'),
        z.literal('CHAT_LINK_CLICK'),
        z.literal('CHAT_RESPONSE'),
        z.literal('COLLAPSE'),
        z.literal('CTA_CLICK'),
        z.literal('DRIVING_DIRECTIONS'),
        z.literal('EVENT'),
        z.literal('EXPAND'),
        z.literal('FEATURED_MESSAGE'),
        z.literal('FILTERING_WITHIN_SECTION'),
        z.literal('FORWARD_PAGINATE'),
        z.literal('HEADER_LINKS'),
        z.literal('ITEM_IN_LIST'),
        z.literal('MAP_CARD'),
        z.literal('MAP_PIN'),
        z.literal('MENU'),
        z.literal('MESSAGE'),
        z.literal('ORDER'),
        z.literal('PAGE_VIEW'),
        z.literal('PAGINATE'),
        z.literal('POST'),
        z.literal('PRESET_PROMPT'),
        z.literal('PRODUCT'),
        z.literal('PROFILE'),
        z.literal('QUESTION_FOCUS'),
        z.literal('QUESTION_SUBMIT'),
        z.literal('REMOVED_FILTER'),
        z.literal('REVIEW'),
        z.literal('SCROLL_TO_BOTTOM_OF_PAGE'),
        z.literal('SEARCH_BAR_IMPRESSION'),
        z.literal('SEARCH_CLEAR_BUTTON'),
        z.literal('TAP_TO_CALL'),
        z.literal('THUMBS_DOWN'),
        z.literal('THUMBS_UP'),
        z.literal('TICKET_URL'),
        z.literal('TITLE'),
        z.literal('VERTICAL_TAB_NAVIGATION'),
        z.literal('VERTICAL_VIEW_ALL'),
        z.literal('VOICE_START'),
        z.literal('VOICE_STOP'),
        z.literal('WEBSITE'),
        z.string().regex(/^[Cc]_[a-zA-Z0-9_-]{1,30}$/)
    ]),
    authorization: z.string().min(1).max(8192).regex(/^(KEY|Bearer)\s.+$/).optional(),
    bot: z.union([
        z.boolean(),
        z.enum(['$auto'])
    ]).optional(),
    browserAgent: z.object({
        browser: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,128}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        browserVersion: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,128}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        device: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,128}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        deviceClass: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,32}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        os: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,128}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        osVersion: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,128}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional(),
        userAgent: z.union([
            z.string().regex(/(?!\$auto$)(^[\x20-\x7E]{1,8192}$)/),
            z.enum(['$auto']),
            z.unknown()
        ]).optional()
    }).optional().default({
        browser: '$auto',
        browserVersion: '$auto',
        device: '$auto',
        deviceClass: '$auto',
        os: '$auto',
        osVersion: '$auto',
        userAgent: '$auto'
    }),
    chat: z.object({
        botId: z.string().min(1).max(50),
        conversationId: z.string().length(48).optional(),
        responseId: z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/).optional()
    }).optional(),
    clientSdk: z.object({
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$': z.string().optional()
    }).optional(),
    count: z.int().gte(1).lte(1000000000).optional().default(1),
    customTags: z.object({
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$': z.string().optional()
    }).optional(),
    customValues: z.object({
        '^[a-zA-Z][a-zA-Z0-9_]{0,31}$': z.number().gte(1).lte(1000000000).optional()
    }).optional(),
    destinationUrl: z.url().optional(),
    entity: z.union([
        z.string().min(1).max(38),
        z.int().gte(0)
    ]).optional(),
    internalUser: z.boolean().optional().default(false),
    ip: z.union([
        z.object({
            address: z.union([
                z.ipv4(),
                z.enum(['$auto'])
            ]),
            algorithm: z.enum(['HASH'])
        }),
        z.unknown()
    ]).optional(),
    label: z.string().min(1).max(16777216).optional(),
    locale: z.union([
        z.string().min(1).max(16).regex(/^(?!(\$auto)$).*$/),
        z.enum(['$auto']),
        z.unknown()
    ]).optional(),
    location: z.union([
        z.object({
            coordinates: z.object({
                latitude: z.number().gte(-90).lte(90),
                longitude: z.number().gte(-180).lte(180)
            })
        }),
        z.string().length(2).regex(/^[A-Za-z]{2}$/)
    ]).optional(),
    pages: z.object({
        scope: z.string().optional(),
        originalEventName: z.string().optional(),
        siteUid: z.int().gte(0).optional(),
        template: z.string().optional()
    }).optional(),
    pageUrl: z.union([
        z.url(),
        z.string(),
        z.unknown()
    ]).optional(),
    referrerUrl: z.union([
        z.url(),
        z.unknown()
    ]).optional(),
    search: z.object({
        searchId: z.string().optional(),
        queryId: z.string().optional(),
        verticalKey: z.string().optional(),
        isDirectAnswer: z.boolean().optional(),
        versionLabel: z.enum(['PRODUCTION', 'STAGING']).optional(),
        versionNumber: z.number().optional(),
        experienceKey: z.string(),
        isGenerativeDirectAnswer: z.boolean().optional()
    }).optional(),
    searchTerm: z.string().min(1).max(16777216).optional(),
    sessionId: z.union([
        z.string().regex(/^[\x20-\x7E]{1,36}$/),
        z.unknown()
    ]).optional(),
    timestamp: z.union([
        z.iso.datetime(),
        z.number().gte(0).lte(3250091520000),
        z.enum(['$auto'])
    ]).optional(),
    value: z.object({
        amount: z.number(),
        currency: z.string().length(3).regex(/^[A-Z]{3}$/)
    }).optional(),
    visitor: z.object({
        '^[a-zA-Z0-9_-]{1,16}$': z.string().regex(/^[\x20-\x7E]{1,64}$/).optional()
    }).optional()
});

/**
 * JSON object containing the events to be sent to Yext Analytics
 */
export const zSendEventsBody = zSendEventsRequestBody;

/**
 * SendEventsResponse
 *
 * Successful request, return analytics event ID that related to this event
 */
export const zSendEventsResponse = z.object({
    id: z.string().optional()
});
