// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { AcceptSuggestionData, AcceptSuggestionErrors, AcceptSuggestionResponses, CancelData, CancelErrors, CancelResponses, DeleteReviewCommentData, DeleteReviewCommentErrors, DeleteReviewCommentResponses, DetailsData, DetailsErrors, DetailsResponses, GetReviewData, GetReviewErrors, GetReviewListData, GetReviewListErrors, GetReviewListResponses, GetReviewResponses, GetSuggestionData, GetSuggestionErrors, GetSuggestionResponses, GetSuggestionsListData, GetSuggestionsListErrors, GetSuggestionsListResponses, OrderData, OrderErrors, OrderResponses, ReviewRespondData, ReviewRespondErrors, ReviewRespondResponses, SearchData, SearchErrors, SearchResponses, SuppressData, SuppressErrors, SuppressResponses, UpdateData, UpdateErrors, UpdateResponses, UpdateReviewCommentData, UpdateReviewCommentErrors, UpdateReviewCommentResponses } from './types.gen.js';
import { zDetailsResponse, zGetReviewListResponse, zGetReviewResponse, zGetSuggestionResponse, zGetSuggestionsListResponse, zOrderResponse, zReviewRespondResponse, zSearchResponse, zUpdateResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Search
 *
 * Yext uses SEARCH to search your site for existing listings. We expect the SEARCH API response to match the search results on your website or mobile app.
 * You should support at least the following search requests:
 * * Phone and Country Code
 * * Name and Lat/Lng OR Name and Address
 *
 */
export const search = <ThrowOnError extends boolean = false>(options?: Options<SearchData, ThrowOnError>): RequestResult<SearchResponses, SearchErrors, ThrowOnError> => (options?.client ?? client).get<SearchResponses, SearchErrors, ThrowOnError>({
    responseValidator: async (data) => await zSearchResponse.parseAsync(data),
    url: '/listings/search',
    ...options
});

/**
 * Details
 *
 * Yext uses DETAILS to retrieve listings details from your site using a known existing listing ID. The Details API should be able to retrieve data for both Yext-powered listings and listings that are in your site’s native format.
 *
 * *NB* For any of the array fields, if there are no items, please default to an empty array, instead of omitting the field, or returning `null`.
 *
 * If the `type` of the listing is `HealthcareProfessional` or `HealthcareFacility`, additional fields are required.
 *
 */
export const details = <ThrowOnError extends boolean = false>(options: Options<DetailsData, ThrowOnError>): RequestResult<DetailsResponses, DetailsErrors, ThrowOnError> => (options.client ?? client).get<DetailsResponses, DetailsErrors, ThrowOnError>({
    responseValidator: async (data) => await zDetailsResponse.parseAsync(data),
    url: '/listings/details',
    ...options
});

/**
 * Order
 *
 * Yext uses ORDER to establish a relationship between an entity in our system with a listing in your system. By sending the ORDER request, Yext will either create a new Listing on your site or claim and update an existing listing that represents the entity. You should include all fields that we pass to you in your listing. Once Yext has successfully sent an ORDER request, the listing content should be “locked”, preventing non-Yext updates to the Yext-updated fields.
 * * Like all of the other real-time API methods, while the ORDER operation uses the POST method, it actually needs to be idempotent for a given yextId.
 * * In the event that a ORDER acknowledgment gets lost, Yext will retry the ORDER operation, which may create duplicates in your index. Therefore, if Yext sends two consecutive ORDER commands using the same yextId, you should re-use the generated id from the first ORDER operation (i.e., you must not create a duplicate listing).
 * * If we send an ORDER request for a listing that has already been claimed by Yext (i.e., the listing's yextId is associated with an id in your system), you should treat the ORDER as an UPDATE and respond accordingly.
 * * For a full list of fields available, including those specific to healthcare and hotels, please reach out to your Yext partner manager or pubops-team@yext.com
 *
 */
export const order = <ThrowOnError extends boolean = false>(options: Options<OrderData, ThrowOnError>): RequestResult<OrderResponses, OrderErrors, ThrowOnError> => (options.client ?? client).post<OrderResponses, OrderErrors, ThrowOnError>({
    responseValidator: async (data) => await zOrderResponse.parseAsync(data),
    url: '/listings/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cancel
 *
 * The CANCEL request is used to notify you when a business cancels their Yext subscription for a given location. This API call effectively undoes an ORDER request.
 * When a listing is CANCELed, we expect you to remove all Yext-specific fields: e.g. Featured Message, attribution logo, Enhanced Content Lists, and pixel tracking from the SERP and profile page.
 * To the extent that the listing was locked for editing / claiming by other data sources, you should remove those restrictions and open the listing for claiming and updates in accordance with your policies.
 * If Yext sends a CANCEL, this should not remove, delete, or revert the listing.
 *
 */
export const cancel = <ThrowOnError extends boolean = false>(options: Options<CancelData, ThrowOnError>): RequestResult<CancelResponses, CancelErrors, ThrowOnError> => (options.client ?? client).delete<CancelResponses, CancelErrors, ThrowOnError>({ url: '/listings/{listingId}', ...options });

/**
 * Update
 *
 * Yext uses UPDATE to update existing Listings on your site.
 * * For a full list of fields available, including those specific to healthcare and hotels, please reach out to your Yext partner manager or pubops-team@yext.com
 *
 */
export const update = <ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>): RequestResult<UpdateResponses, UpdateErrors, ThrowOnError> => (options.client ?? client).put<UpdateResponses, UpdateErrors, ThrowOnError>({
    responseValidator: async (data) => await zUpdateResponse.parseAsync(data),
    url: '/listings/{listingId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Suppress
 *
 * This call allows Yext to suppress duplicate or invalid listings. If a listing is SUPPRESSed, we expect you to exclude the listing from your site's search results. Going to the SUPPRESSed listing's URL should result in either a 404 error, redirect to the SERP, or a redirect to the listing specified in canonicalListingId. Only non-Yext listings are suppressed: We only suppress listings that are not powered by Yext. We do not suppress listings that we sync data to.
 * * Yext will indicate to the publisher that a listing must be suppressed, optionally providing the id of a listing that it duplicates (the “canonical” listing). The publisher must comply within 24 hours by taking the following actions:
 * * The listing should be marked as suppressed in Search and Details API responses. Alternatively, the listing can be excluded from your Search API response.
 * * The publisher must exclude the suppressed listing from their search index.
 * * If a canonical listing ID is provided, the publisher must place a redirect to send users that access the suppressed listing’s profile page to the canonical listing’s profile page.
 * * Conversely, Yext may indicate to the publisher that a listing suppression should be reverted.
 * * The listing should have an AVAILABLE status in your Search and Details API response
 * * The publisher should revert the listing back to its original state
 * * Calls should be idempotent; for example, the publisher should report success and do nothing if Yext attempts to suppress a listing that is already suppressed.
 *
 */
export const suppress = <ThrowOnError extends boolean = false>(options?: Options<SuppressData, ThrowOnError>): RequestResult<SuppressResponses, SuppressErrors, ThrowOnError> => (options?.client ?? client).post<SuppressResponses, SuppressErrors, ThrowOnError>({
    url: '/listings/suppress',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Review List
 *
 * Yext uses REVIEWS to retrieve review data for business owners. You should provide access to all organic reviews displayed on your properties (i.e., no third-party reviews).
 *
 * ## **Requirements**
 * When Yext customers sign in to their Listings dashboard, Yext shows them all their reviews from across the Yext Knowledge Network. In order to support this, we have the following requirements for any publisher that supports customer reviews on their listings.
 *
 * * Publisher must provide access to all review data.
 * * Publisher’s system must notify Yext when new reviews are added, updated, or deleted from Yext-powered listings.
 * * Publisher must provide a direct link to each individual review.
 * * If the publisher allows users to respond to reviews, the publisher must allow Yext to do so (on behalf of the business owner).
 * * If the publisher allows users to flag reviews as abuse, the publisher must allow Yext to do so (on behalf of the business owner).
 *
 */
export const getReviewList = <ThrowOnError extends boolean = false>(options: Options<GetReviewListData, ThrowOnError>): RequestResult<GetReviewListResponses, GetReviewListErrors, ThrowOnError> => (options.client ?? client).get<GetReviewListResponses, GetReviewListErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetReviewListResponse.parseAsync(data),
    url: '/listings/reviews',
    ...options
});

/**
 * Get Review
 *
 * Get the review object for a specific review ID.
 *
 */
export const getReview = <ThrowOnError extends boolean = false>(options: Options<GetReviewData, ThrowOnError>): RequestResult<GetReviewResponses, GetReviewErrors, ThrowOnError> => (options.client ?? client).get<GetReviewResponses, GetReviewErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetReviewResponse.parseAsync(data),
    url: '/listings/reviews/{reviewId}',
    ...options
});

/**
 * Create Comment
 *
 * Yext uses RESPOND to allow business owners to interact with reviews left by consumers.
 * The endpoint supports review response by a business owner and the capability to flag reviews for inappropriate content. You should support any capabilities you already have on your site.
 *
 * # **Requirements**
 * Yext's customers would like to be able to manage all their reviews from one platform. To that end, they should be able to use the Yext platform to take advantage of the review-management features you have on your site.
 * ## Specifically:
 * * Publishers who support review response from business owners must provide that capability via this endpoint.
 * * Publishers who support flagging reviews for inappropriate content must provide that capability via this endpoint.
 *
 */
export const reviewRespond = <ThrowOnError extends boolean = false>(options: Options<ReviewRespondData, ThrowOnError>): RequestResult<ReviewRespondResponses, ReviewRespondErrors, ThrowOnError> => (options.client ?? client).post<ReviewRespondResponses, ReviewRespondErrors, ThrowOnError>({
    responseValidator: async (data) => await zReviewRespondResponse.parseAsync(data),
    url: '/listings/reviews/{reviewId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Comment
 *
 * Yext uses the DELETE operation to remove a review comment from the business owner on a specific review.
 *
 */
export const deleteReviewComment = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewCommentData, ThrowOnError>): RequestResult<DeleteReviewCommentResponses, DeleteReviewCommentErrors, ThrowOnError> => (options.client ?? client).delete<DeleteReviewCommentResponses, DeleteReviewCommentErrors, ThrowOnError>({ url: '/listings/reviews/{reviewId}/comment/{commentId}', ...options });

/**
 * Update Comment
 *
 * Yext uses the PUT operation to update a review comment from the business owner on a specific review.
 *
 */
export const updateReviewComment = <ThrowOnError extends boolean = false>(options: Options<UpdateReviewCommentData, ThrowOnError>): RequestResult<UpdateReviewCommentResponses, UpdateReviewCommentErrors, ThrowOnError> => (options.client ?? client).put<UpdateReviewCommentResponses, UpdateReviewCommentErrors, ThrowOnError>({
    url: '/listings/reviews/{reviewId}/comment/{commentId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Suggestion List
 *
 * Yext uses Suggestions: List to retrieve all active suggestions data for business owners. You should provide access to all suggestions in status “PENDING”.
 *
 */
export const getSuggestionsList = <ThrowOnError extends boolean = false>(options: Options<GetSuggestionsListData, ThrowOnError>): RequestResult<GetSuggestionsListResponses, GetSuggestionsListErrors, ThrowOnError> => (options.client ?? client).get<GetSuggestionsListResponses, GetSuggestionsListErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetSuggestionsListResponse.parseAsync(data),
    url: '/listings/suggestions',
    ...options
});

/**
 * Single Suggestion
 *
 * Yext uses Suggestions: Get to retrieve the suggestion object for a specific suggestion ID.
 *
 */
export const getSuggestion = <ThrowOnError extends boolean = false>(options: Options<GetSuggestionData, ThrowOnError>): RequestResult<GetSuggestionResponses, GetSuggestionErrors, ThrowOnError> => (options.client ?? client).get<GetSuggestionResponses, GetSuggestionErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetSuggestionResponse.parseAsync(data),
    url: '/listings/suggestions/{suggestionId}',
    ...options
});

/**
 * Suggestion Accept
 *
 * Yext uses Accept/Reject to indicate whether a suggestion object has been accepted or rejected by the user.
 *
 */
export const acceptSuggestion = <ThrowOnError extends boolean = false>(options: Options<AcceptSuggestionData, ThrowOnError>): RequestResult<AcceptSuggestionResponses, AcceptSuggestionErrors, ThrowOnError> => (options.client ?? client).put<AcceptSuggestionResponses, AcceptSuggestionErrors, ThrowOnError>({
    url: '/listings/suggestions/{suggestionId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
