// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * The status of the listing
 */
export const zListingStatus = z.enum([
    'AVAILABLE',
    'ACTIVE',
    'CLAIMED',
    'SUPPRESSED',
    'BLOCKED'
]);

/**
 * List of business categories, in your taxonomy, ordered by importance / relevance
 */
export const zCategories = z.array(z.object({
    id: z.string(),
    name: z.string()
}));

/**
 * The kind of listing
 */
export const zLocationType = z.enum([
    'Location',
    'HealthcareFacility',
    'HealthcareProfessional'
]);

export const zSearchResult = z.object({
    id: z.string(),
    status: zListingStatus,
    name: z.string(),
    address: z.string(),
    address2: z.string().optional(),
    sublocality: z.string().optional(),
    city: z.string(),
    state: z.string().optional(),
    zip: z.string().optional(),
    countryCode: z.string(),
    latitude: z.number(),
    longitude: z.number(),
    phone: z.string(),
    url: z.string(),
    categories: zCategories,
    type: zLocationType,
    websiteUrl: z.string().optional(),
    reviewCount: z.int().optional(),
    averageReviewScore: z.number().optional(),
    listingCreationDate: z.string().optional()
});

export const zResponseErrorNew = z.object({
    code: z.int().optional(),
    message: z.string().optional()
});

/**
 * The hours associated with the listing.
 */
export const zDetailsHours = z.array(z.object({
    day: z.enum([
        'MONDAY',
        'TUESDAY',
        'WEDNESDAY',
        'THURSDAY',
        'FRIDAY',
        'SATURDAY',
        'SUNDAY'
    ]).optional(),
    intervals: z.array(z.object({
        start: z.string().optional(),
        end: z.string().optional()
    })).optional()
}));

/**
 * The closed status of the listing
 */
export const zClosedStatus = z.enum([
    'OPEN',
    'TEMPORARILY_CLOSED',
    'PERMANENTLY_CLOSED'
]);

/**
 * Base fields for any type of listing
 */
export const zDetails = z.object({
    id: z.string(),
    status: zListingStatus,
    name: z.string(),
    address: z.string(),
    address2: z.string().optional(),
    sublocality: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    countryCode: z.string().optional(),
    phone: z.string(),
    url: z.string(),
    rating: z.number().optional(),
    totalReviews: z.int().optional(),
    categories: zCategories.optional(),
    website: z.string().optional(),
    description: z.string().optional(),
    hours: zDetailsHours,
    photos: z.array(z.string()).optional(),
    yearEstablished: z.int().optional(),
    specialOfferMessage: z.string().optional(),
    specialOfferUrl: z.string().optional(),
    contactEmail: z.string().optional(),
    latitude: z.string(),
    longitude: z.string(),
    video: z.string().optional(),
    paymentOptions: z.array(z.string()).optional(),
    twitter: z.string().optional(),
    facebook: z.string().optional(),
    type: zLocationType.optional(),
    closedStatus: zClosedStatus
});

/**
 * The following additional fields are available if `type` is `HealthcareProfessional`.
 */
export const zHealthcareProfessional = z.object({
    npi: z.string(),
    firstName: z.string(),
    middleName: z.string(),
    lastName: z.string(),
    officeName: z.string(),
    gender: z.string(),
    conditionsTreated: z.array(z.string()).optional(),
    acceptingNewPatients: z.boolean().optional().default(true)
});

/**
 * The following additional fields are available if `type` is `HealthcareFacility`.
 */
export const zHealthcareFacility = z.object({
    npi: z.string(),
    conditionsTreated: z.array(z.string()).optional(),
    acceptingNewPatients: z.boolean().optional().default(true)
});

/**
 * The structured address for the location
 */
export const zAddress = z.object({
    address: z.string(),
    address2: z.string(),
    displayAddress: z.string().optional(),
    visible: z.boolean().optional(),
    sublocality: z.string().optional(),
    city: z.string(),
    state: z.string(),
    postalCode: z.string(),
    countryCode: z.string()
});

/**
 * A list of the location’s phone numbers. There will be exactly one MAIN phone number and optionally some non-MAIN phone numbers (at most one of each type).
 */
export const zPhones = z.array(z.object({
    description: z.string().optional(),
    number: z.object({
        countryCode: z.string().optional(),
        number: z.string().optional()
    }),
    type: z.enum([
        'MAIN',
        'ALTERNATE',
        'FAX',
        'LOCAL',
        'MOBILE',
        'TOLL_FREE',
        'TTY'
    ]).optional()
}));

/**
 * List of business categories, in your taxonomy, ordered by importance / relevance
 */
export const zPartnerCategories = z.array(z.object({
    id: z.string(),
    name: z.string()
}));

/**
 * A list of contact email addresses that consumers can use to reach someone who represents the location
 */
export const zEmails = z.array(z.object({
    address: z.string().optional(),
    description: z.string().optional()
}));

/**
 * Geolocation data describing where exactly the physical location is
 */
export const zGeoData = z.object({
    displayLatitude: z.number(),
    displayLongitude: z.number(),
    routableLatitude: z.number().optional(),
    routableLongitude: z.number().optional(),
    walkingLatitude: z.number().optional(),
    walkingLongitude: z.number().optional()
});

/**
 * A set of opening and closing times for the specified date.
 */
export const zInterval = z.array(z.object({
    start: z.string().optional(),
    end: z.string().optional()
}));

/**
 * A set of special hours that may vary from the standard business hours.
 */
export const zHolidayHour = z.array(z.object({
    date: z.string().optional(),
    isClosed: z.boolean().optional(),
    isRegularHours: z.boolean().optional(),
    intervals: z.array(zInterval).optional()
}));

/**
 * Contains structured business-hours information. Any days that are unspecified should be interpreted as 'we don't have information for this day'. Days that are specified, but contain no times, should be interpreted as 'Closed'. This is not a required field in Yext but should be displayed if provided.
 */
export const zHours = z.object({
    day: z.enum([
        'MONDAY',
        'TUESDAY',
        'WEDNESDAY',
        'THURSDAY',
        'FRIDAY',
        'SATURDAY',
        'SUNDAY'
    ]).optional(),
    intervals: z.array(zInterval).optional(),
    reopenDate: z.string().optional(),
    holidayHours: z.array(zHolidayHour).optional()
});

/**
 * Contains the daily access hours, holiday access hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `accessHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday access hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 *
 * Filtering Type: `hours`
 *
 * ```
 * Eligible For:
 * * atm
 * * healthcareFacility
 * * hotel
 * * location
 * * restaurant
 * ```
 */
export const zAccessHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily brunch hours, holiday brunch hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `brunchHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday brunch hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zBrunchHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily delivery hours, holiday delivery hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `deliveryHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday delivery hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zDeliveryHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily drive-through hours, holiday drive-through hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `driveThroughHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday drive-through hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zDriveThroughHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily happy hours, holiday happy hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `happyHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday happy hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zHappyHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily kitchen hours, holiday kitchen hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `kitchenHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday kitchen hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zKitchenHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily online service hours, holiday online service hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `onlineServiceHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday online service hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zOnlineServiceHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily pickup hours, holiday pickup hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `pickupHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday pickup hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zPickupHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily senior hours, holiday senior hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `seniorHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday senior hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zSeniorHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * Contains the daily takeout hours, holiday takeout hours, and reopen date for the Entity.
 *
 * Each day is represented by a sub-field of `takeoutHours`. (e.g. `monday`, `tuesday`, etc.) Open times can be specified per day through the `openIntervals` field and the `isClosed` flag.
 * Similarly, holiday takeout hours are represented by the `holidayHours` sub-field.
 * Setting the `reopenDate` sub-field indicates that the business is temporarily closed and will reopen on the specified date.
 * SPECIAL CASES:
 * * To indicate that an Entity is open 24 hours on a specific day, set start to 00:00 and end to 23:59 in `openIntervals` for that day.
 * * To indicate that an Entity has split hours on a specific day (e.g., open from 9:00 AM to 12:00 PM and again from 1:00 PM to 5:00 PM), supply two or more `openIntervals` values with non-overlapping sets of hours.
 * * If you are providing `openIntervals`, you may not set `isClosed` to true for that day.
 */
export const zTakeoutHours = z.object({
    friday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    holidayHours: z.array(z.object({
        date: z.iso.date(),
        isClosed: z.boolean().optional(),
        isRegularHours: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    })).optional(),
    monday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    reopenDate: z.iso.date().optional(),
    saturday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    sunday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    thursday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    tuesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional(),
    wednesday: z.object({
        isClosed: z.boolean().optional(),
        openIntervals: z.array(z.object({
            end: z.iso.time().optional(),
            start: z.iso.time().optional()
        })).optional()
    }).optional()
});

/**
 * You should be able to support and maintain the image size of the photo passed by Yext. We will not send you photos greater than 5MB.
 */
export const zImage = z.object({
    url: z.string().optional(),
    type: z.enum([
        'LOGO',
        'STOREFRONT',
        'GALLERY',
        'HEADSHOT'
    ]).optional(),
    width: z.int().optional(),
    height: z.int().optional(),
    description: z.string().optional()
});

/**
 * YouTube videos specified by the business
 */
export const zVideo = z.object({
    url: z.string().optional(),
    description: z.string().optional()
});

/**
 * The featured message of the location
 */
export const zFeaturedMessage = z.object({
    message: z.string().optional(),
    url: z.string().optional()
});

export const zUrl = z.object({
    url: z.string().optional(),
    type: z.enum([
        'WEBSITE',
        'RESERVATION',
        'MENU',
        'ORDER'
    ]).optional(),
    displayUrl: z.string().optional()
});

/**
 * Listing attribution to whomever the business bought Listings from (i.e., Yext or one of Yext's partners)
 */
export const zAttribution = z.object({
    image: z.object({
        url: z.string().optional(),
        description: z.string().optional(),
        width: z.int().optional(),
        height: z.int().optional()
    }).optional()
});

export const zEclid = z.object({
    id: z.number().optional(),
    type: z.enum([
        'MENU',
        'PRODUCTS',
        'EVENTS',
        'BIOS'
    ]).optional(),
    description: z.string().optional(),
    name: z.string().optional()
});

export const zFrequentlyAskedQuestion = z.object({
    question: z.string().optional(),
    answer: z.string().optional()
});

export const zListingDelivery = z.object({
    yextId: z.string().optional(),
    partnerId: z.string().optional(),
    name: z.string().optional(),
    address: zAddress.optional(),
    geomodifier: z.string().optional(),
    phones: z.array(zPhones).optional(),
    categories: z.array(zPartnerCategories).optional(),
    description: z.string().optional(),
    emails: z.array(zEmails).optional(),
    geodata: zGeoData.optional(),
    hours: z.array(zHours).optional(),
    accessHours: zAccessHours.optional(),
    brunchHours: zBrunchHours.optional(),
    deliveryHours: zDeliveryHours.optional(),
    driveThroughHours: zDriveThroughHours.optional(),
    happyHours: zHappyHours.optional(),
    kitchenHours: zKitchenHours.optional(),
    onlineServiceHours: zOnlineServiceHours.optional(),
    pickupHours: zPickupHours.optional(),
    seniorHours: zSeniorHours.optional(),
    takeoutHours: zTakeoutHours.optional(),
    images: z.array(zImage).optional(),
    videos: z.array(zVideo).optional(),
    featuredMessage: zFeaturedMessage.optional(),
    paymentOptions: z.array(z.string()).optional(),
    urls: z.array(zUrl).optional(),
    twitterHandle: z.string().optional(),
    facebookPageUrl: z.string().optional(),
    instagramHandle: z.string().optional(),
    attribution: zAttribution.optional(),
    keywords: z.array(z.string()).optional(),
    lists: z.array(zEclid).optional(),
    closed: z.boolean().optional(),
    closeDate: z.string().optional(),
    reopenDate: z.string().optional(),
    pickupAndDeliveryOptions: z.array(z.enum([
        'INSTORE_PICKUP',
        'CURBSIDE_PICKUP',
        'DELIVERY',
        'SAME_DAY_DELIVERY',
        'NO_CONTACT_DELIVERY'
    ])).optional(),
    specialties: z.array(z.string()).optional(),
    brands: z.array(z.string()).optional(),
    products: z.array(z.string()).optional(),
    services: z.array(z.string()).optional(),
    yearEstablished: z.string().optional(),
    associations: z.array(z.string()).optional(),
    languages: z.array(z.string()).optional(),
    frequentlyAskedQuestions: z.array(zFrequentlyAskedQuestion).optional(),
    blackOwnedBusiness: z.boolean().optional(),
    priceRange: z.enum([
        '$',
        '$$',
        '$$$',
        '$$$$'
    ]).optional(),
    neighborhood: z.string().optional()
});

export const zResponseMeta = z.object({
    uuid: z.string().optional()
});

export const zResponseError = z.object({
    code: z.int().optional(),
    type: z.enum([
        'FATAL_ERROR',
        'NON_FATAL_ERROR',
        'WARNING'
    ]).optional(),
    message: z.string().optional()
});

export const zResponseMetaWithError = zResponseMeta.and(z.object({
    errors: z.array(zResponseError).optional()
}));

export const zSuppressionRequest = z.object({
    listingId: z.string().optional(),
    supress: z.boolean().optional(),
    canonicalListingId: z.string().optional()
});

/**
 * List of comments on the review
 */
export const zPartnerReviewComments = z.array(z.object({
    commentId: z.string(),
    timestamp: z.string(),
    authorName: z.string(),
    content: z.string(),
    ownerResponse: z.boolean().optional()
}));

export const zPartnerReview = z.object({
    reviewId: z.string(),
    status: z.enum(['ACTIVE', 'SUPPRESSED']),
    timestamp: z.string(),
    authorName: z.string(),
    title: z.string().optional(),
    content: z.string().optional(),
    url: z.string(),
    rating: z.string().optional(),
    maxRating: z.string().optional(),
    flagReason: z.enum([
        'INAPPROPRIATE_CONTENT',
        'SPAM',
        'NOT_LOCATION_RELATED'
    ]).optional(),
    comments: zPartnerReviewComments.optional(),
    generated: z.boolean().optional()
});

export const zPartnerReviewList = z.object({
    total: z.int(),
    rating: z.number(),
    maxRating: z.int(),
    reviews: z.array(zPartnerReview).optional()
});

export const zPartnerReviewResponse = z.object({
    reviewId: z.string().optional(),
    flagReason: z.enum([
        'INAPPROPRIATE_CONTENT',
        'SPAM',
        'NOT_LOCATION_RELATED'
    ]).optional(),
    comment: z.string().optional()
});

export const zPartnerReviewResponseUpdate = z.object({
    reviewId: z.string().optional(),
    flagReason: z.enum([
        'INAPPROPRIATE_CONTENT',
        'SPAM',
        'NOT_LOCATION_RELATED'
    ]).optional(),
    commentId: z.string().optional(),
    comment: z.string().optional()
});

export const zPartnerSuggestion = z.object({
    id: z.string(),
    field: z.string(),
    status: z.enum([
        'ACCEPTED',
        'PENDING',
        'REJECTED',
        'EXPIRED'
    ]),
    timestamp: z.string(),
    currentValue: z.string().optional(),
    proposedValue: z.string()
});

export const zPartnerSuggestionList = z.object({
    total: z.int(),
    suggestions: z.array(zPartnerSuggestion)
});

/**
 * The request body of a suggestion accept/reject
 */
export const zSuggestionAcceptBody = z.object({
    suggestionId: z.string(),
    accept: z.enum(['ACTIVE', 'SUPPRESSED'])
});

/**
 * Business name.
 *
 * e.g. `Yext`
 *
 */
export const zName = z.string();

/**
 * Street address, including house numbers, to search.
 *
 * e.g `75 9th Ave`, `Bismarckstraße 35`
 *
 */
export const zAddress2 = z.string();

/**
 * Address line 2 to search.
 *
 * e.g. `7th floor`
 *
 */
export const zAddress22 = z.string();

/**
 * Sublocality (e.g., neighborhood, ward or district) in which to search.
 *
 * e.g. `pos. Lesnoe` (Russia), `Saiwai-ku` (Japan)
 *
 */
export const zSublocality = z.string();

/**
 * City in which to search
 *
 * e.g. `New York`
 *
 */
export const zLocality = z.string();

/**
 * State, region, or province in which to search. Abbreviations are used for some countries.
 *
 * e.g. `NY`, `Kanagawa`
 *
 */
export const zRegion = z.string();

/**
 * ZIP or postal code in which to search.
 *
 * e.g. `10011`, `212-0011`, `4841 EP`
 *
 */
export const zPostalCode = z.string();

/**
 * The ISO 3166-1 alpha-2 code of the country in which to search.
 *
 * e.g. `GB`, `NL`, `GB`
 *
 */
export const zCountry = z.string();

/**
 * Location's phone number.
 * For international numbers, this number reflects how the number is dialed within the country (i.e., no country code or punctuation).
 *
 * e.g. `2126518966`
 *
 */
export const zPhone = z.string();

/**
 * latitude and longitude coordinates, separated by a comma.
 *
 * e.g. `-27.1259105,-109.4789002`
 *
 */
export const zLatlng = z.string();

/**
 * The first name of the healthcare professional whose records should be returned.
 *
 * NOTE: You only need to support this parameter if your site supports first/last name search.
 *
 */
export const zFirstName = z.string();

/**
 * The last name of the healthcare professional whose records should be returned.
 *
 * NOTE: You only need to support this parameter if your site supports first/last name search.
 *
 */
export const zLastName = z.string();

/**
 * National Provider Identifier (NPI) of the healthcare professional or facility whose records should be returned.
 *
 * NOTE: This parameter will only be used if you have NPI data.
 *
 */
export const zNpi = z.string();

/**
 * The kind of records that should be returned.
 *
 * NOTE: This parameter will only be used if you support more than just the `Location` type.
 *
 */
export const zType = z.enum([
    'Location',
    'HealthcareFacility',
    'HealthcareProfessional'
]);

/**
 * The unique identifier of a listing on your site is known as the listingId.
 *
 */
export const zListingId = z.string();

/**
 * The number of reviews to return
 *
 */
export const zNum = z.string();

/**
 * An ISO-8601 date-time that filters results to those reviews posted before this time (exclusive). If not specified, no filter should be applied.
 * NOTE: This parameter is used to page through results. For example, Yext may fetch the newest 10 reviews and make a subsequent request with before set to the last review's timestamp in order to fetch the second page.
 *
 */
export const zBefore = z.string();

/**
 * ID of this Review.
 */
export const zReviewId = z.int();

/**
 * The review comment’s ID on your site
 *
 */
export const zCommentId = z.string();

/**
 * The unique identifier of a suggestion on your site is known as the suggestionId.
 *
 */
export const zSuggestionId = z.string();

export const zSearchQuery = z.object({
    name: z.string().optional(),
    address: z.string().optional(),
    address2: z.string().optional(),
    sublocality: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    countryCode: z.string().optional(),
    phone: z.string().optional(),
    latlng: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    npi: z.string().optional(),
    type: z.enum([
        'Location',
        'HealthcareFacility',
        'HealthcareProfessional'
    ]).optional()
});

/**
 * SearchSuccess
 *
 * A list of search results; empty if no matching listings could be found.
 */
export const zSearchResponse = z.array(zSearchResult);

export const zDetailsQuery = z.object({
    id: z.string()
});

/**
 * DetailsResponse
 *
 * OK
 */
export const zDetailsResponse = z.union([
    zDetails,
    zHealthcareProfessional,
    zHealthcareFacility
]);

export const zOrderBody = zListingDelivery;

/**
 * LiveResponse
 *
 * OK
 */
export const zOrderResponse = z.object({
    status: z.string().optional(),
    id: z.string().optional(),
    url: z.string().optional()
});

export const zCancelPath = z.object({
    listingId: z.string()
});

export const zUpdateBody = zListingDelivery;

export const zUpdatePath = z.object({
    listingId: z.string()
});

/**
 * LiveResponse
 *
 * OK
 */
export const zUpdateResponse = z.object({
    status: z.string().optional(),
    id: z.string().optional(),
    url: z.string().optional()
});

export const zSuppressBody = zSuppressionRequest;

export const zGetReviewListQuery = z.object({
    listingId: z.string(),
    num: z.string(),
    before: z.string().optional()
});

/**
 * OK
 */
export const zGetReviewListResponse = zPartnerReviewList;

export const zGetReviewPath = z.object({
    reviewId: z.int()
});

/**
 * OK
 */
export const zGetReviewResponse = zPartnerReview;

export const zReviewRespondBody = zPartnerReviewResponse;

export const zReviewRespondPath = z.object({
    reviewId: z.int()
});

/**
 * NewCommentSuccess
 *
 * OK
 */
export const zReviewRespondResponse = z.object({
    commentId: z.string().optional()
});

export const zDeleteReviewCommentPath = z.object({
    reviewId: z.int(),
    commentId: z.string()
});

export const zUpdateReviewCommentBody = zPartnerReviewResponseUpdate;

export const zUpdateReviewCommentPath = z.object({
    reviewId: z.int(),
    commentId: z.string()
});

export const zGetSuggestionsListQuery = z.object({
    listingId: z.string()
});

/**
 * OK
 */
export const zGetSuggestionsListResponse = zPartnerSuggestionList;

export const zGetSuggestionPath = z.object({
    suggestionId: z.string()
});

/**
 * OK
 */
export const zGetSuggestionResponse = zPartnerSuggestion;

export const zAcceptSuggestionBody = zSuggestionAcceptBody;

export const zAcceptSuggestionPath = z.object({
    suggestionId: z.string()
});
