// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { ContentGetData, ContentGetErrors, ContentGetResponses, ContentListData, ContentListErrors, ContentListResponses, CreateQuestionData, CreateQuestionErrors, CreateQuestionResponses, CreateReviewData, CreateReviewErrors, CreateReviewResponses, DeleteReviewData, DeleteReviewErrors, DeleteReviewResponses, GeoSearchData, GeoSearchEntitiesData, GeoSearchEntitiesErrors, GeoSearchEntitiesResponses, GeoSearchErrors, GeoSearchResponses, GetBiosData, GetBiosErrors, GetBiosResponses, GetEntityData, GetEntityErrors, GetEntityResponses, GetEntitySchemaData, GetEntitySchemaErrors, GetEntitySchemaResponses, GetEventsData, GetEventsErrors, GetEventsResponses, GetLanguageProfileData, GetLanguageProfileErrors, GetLanguageProfileResponses, GetLanguageProfilesData, GetLanguageProfilesErrors, GetLanguageProfilesResponses, GetLanguageProfilesSchemaData, GetLanguageProfilesSchemaErrors, GetLanguageProfilesSchemaResponses, GetLocationData, GetLocationErrors, GetLocationResponses, GetLocationSchemaData, GetLocationSchemaErrors, GetLocationSchemaResponses, GetMenusData, GetMenusErrors, GetMenusResponses, GetProductsData, GetProductsErrors, GetProductsResponses, ListAllLanguageProfilesData, ListAllLanguageProfilesErrors, ListAllLanguageProfilesResponses, ListEntitiesData, ListEntitiesErrors, ListEntitiesResponses, ListLanguageProfilesData, ListLanguageProfilesErrors, ListLanguageProfilesResponses, ListLocationLanguageProfilesData, ListLocationLanguageProfilesErrors, ListLocationLanguageProfilesResponses, LocationsListData, LocationsListErrors, LocationsListResponses, UpdateReviewData, UpdateReviewErrors, UpdateReviewResponses } from './types.gen.js';
import { zContentGetResponse, zContentListResponse, zCreateQuestionResponse, zCreateReviewResponse, zDeleteReviewResponse, zGeoSearchEntitiesResponse, zGeoSearchResponse, zGetBiosResponse, zGetEntityResponse, zGetEntitySchemaResponse, zGetEventsResponse, zGetLanguageProfileResponse, zGetLanguageProfilesResponse, zGetLanguageProfilesSchemaResponse, zGetLocationResponse, zGetLocationSchemaResponse, zGetMenusResponse, zGetProductsResponse, zListAllLanguageProfilesResponse, zListEntitiesResponse, zListLanguageProfilesResponse, zListLocationLanguageProfilesResponse, zLocationsListResponse, zUpdateReviewResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Entities: List
 *
 * Retrieve a list of Entities within an account
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const listEntities = <ThrowOnError extends boolean = false>(options: Options<ListEntitiesData, ThrowOnError>): RequestResult<ListEntitiesResponses, ListEntitiesErrors, ThrowOnError> => (options.client ?? client).get<ListEntitiesResponses, ListEntitiesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListEntitiesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entities',
    ...options
});

/**
 * Entities: Get
 *
 * Retrieve information for an Entity with a given ID
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const getEntity = <ThrowOnError extends boolean = false>(options: Options<GetEntityData, ThrowOnError>): RequestResult<GetEntityResponses, GetEntityErrors, ThrowOnError> => (options.client ?? client).get<GetEntityResponses, GetEntityErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetEntityResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entities/{entityId}',
    ...options
});

/**
 * Entities: GeoSearch
 *
 * Gets multiple Entities with addresses near a given geographical point,
 * ordered by proximity to that point and restricted to a radius.
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const geoSearchEntities = <ThrowOnError extends boolean = false>(options: Options<GeoSearchEntitiesData, ThrowOnError>): RequestResult<GeoSearchEntitiesResponses, GeoSearchEntitiesErrors, ThrowOnError> => (options.client ?? client).get<GeoSearchEntitiesResponses, GeoSearchEntitiesErrors, ThrowOnError>({
    responseValidator: async (data) => await zGeoSearchEntitiesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entities/geosearch',
    ...options
});

/**
 * Entities Schema: Get
 *
 * Gets the schema.org-compliant schema for the primary profile of a single Entity. Schema will vary depending on entity type.
 */
export const getEntitySchema = <ThrowOnError extends boolean = false>(options: Options<GetEntitySchemaData, ThrowOnError>): RequestResult<GetEntitySchemaResponses, GetEntitySchemaErrors, ThrowOnError> => (options.client ?? client).get<GetEntitySchemaResponses, GetEntitySchemaErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetEntitySchemaResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entityschema/{entityType}/{entityId}/{languageCode}',
    ...options
});

/**
 * Entity Language Profiles: Get
 *
 * Retrieve a Language Profile for an Entity
 *
 * **NOTE:**
 *
 * * Responses will contain resolved values for embedded fields
 * * If the `fields` parameter is unspecified, responses will contain the full
 * entity profile for the requested language
 *
 */
export const getLanguageProfile = <ThrowOnError extends boolean = false>(options: Options<GetLanguageProfileData, ThrowOnError>): RequestResult<GetLanguageProfileResponses, GetLanguageProfileErrors, ThrowOnError> => (options.client ?? client).get<GetLanguageProfileResponses, GetLanguageProfileErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetLanguageProfileResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entityprofiles/{entityId}/{languageCode}',
    ...options
});

/**
 * Entity Language Profiles: List
 *
 * Retrieve Language Profiles for an Entity
 *
 * **NOTE:**
 *
 * * Responses will contain resolved values for embedded fields
 * * If the `fields` parameter is unspecified, responses will contain the full
 * entity profile for the requested language
 *
 */
export const listLanguageProfiles = <ThrowOnError extends boolean = false>(options: Options<ListLanguageProfilesData, ThrowOnError>): RequestResult<ListLanguageProfilesResponses, ListLanguageProfilesErrors, ThrowOnError> => (options.client ?? client).get<ListLanguageProfilesResponses, ListLanguageProfilesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListLanguageProfilesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entityprofiles/{entityId}',
    ...options
});

/**
 * Entity Language Profiles: List All
 *
 * Retrieve a list of Language Profiles for Entities within an account
 *
 * **NOTE:**
 *
 * * Responses will contain resolved values for embedded fields
 * * If the `fields` parameter is unspecified, responses will contain the full
 * entity profile for the requested language
 *
 */
export const listAllLanguageProfiles = <ThrowOnError extends boolean = false>(options: Options<ListAllLanguageProfilesData, ThrowOnError>): RequestResult<ListAllLanguageProfilesResponses, ListAllLanguageProfilesErrors, ThrowOnError> => (options.client ?? client).get<ListAllLanguageProfilesResponses, ListAllLanguageProfilesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListAllLanguageProfilesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/entityprofiles',
    ...options
});

/**
 * Menus: Get
 *
 * Retrieve a specific Menu
 */
export const getMenus = <ThrowOnError extends boolean = false>(options: Options<GetMenusData, ThrowOnError>): RequestResult<GetMenusResponses, GetMenusErrors, ThrowOnError> => (options.client ?? client).get<GetMenusResponses, GetMenusErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetMenusResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/menus/{listId}',
    ...options
});

/**
 * Bios: Get
 *
 * Retrieve a specific Bios ECL
 */
export const getBios = <ThrowOnError extends boolean = false>(options: Options<GetBiosData, ThrowOnError>): RequestResult<GetBiosResponses, GetBiosErrors, ThrowOnError> => (options.client ?? client).get<GetBiosResponses, GetBiosErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetBiosResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/bios/{listId}',
    ...options
});

/**
 * Products: Get
 *
 * Retrieve a specific Products ECL
 */
export const getProducts = <ThrowOnError extends boolean = false>(options: Options<GetProductsData, ThrowOnError>): RequestResult<GetProductsResponses, GetProductsErrors, ThrowOnError> => (options.client ?? client).get<GetProductsResponses, GetProductsErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetProductsResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/products/{listId}',
    ...options
});

/**
 * Events (Legacy): Get
 *
 * Retrieve a specific Events ECL
 */
export const getEvents = <ThrowOnError extends boolean = false>(options: Options<GetEventsData, ThrowOnError>): RequestResult<GetEventsResponses, GetEventsErrors, ThrowOnError> => (options.client ?? client).get<GetEventsResponses, GetEventsErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetEventsResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/events/{listId}',
    ...options
});

/**
 * Language Profiles (Legacy): Get
 *
 * Gets the requested Language Profile for a given Location
 *
 * **NOTE:**
 * * Responses will contain resolved values for embedded fields
 * * If the `fields` parameter is unspecified, responses will contain the full
 * entity profile for the requested language
 *
 */
export const getLanguageProfiles = <ThrowOnError extends boolean = false>(options: Options<GetLanguageProfilesData, ThrowOnError>): RequestResult<GetLanguageProfilesResponses, GetLanguageProfilesErrors, ThrowOnError> => (options.client ?? client).get<GetLanguageProfilesResponses, GetLanguageProfilesErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetLanguageProfilesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/{locationId}/profiles/{languageCode}',
    ...options
});

/**
 * Language Profiles (Legacy): List
 *
 * Gets all Language Profiles for a Location
 *
 * **NOTE:**
 * * Responses will contain resolved values for embedded fields
 * * If the `fields` parameter is unspecified, responses will contain the full
 * entity profile for the requested language
 *
 */
export const listLocationLanguageProfiles = <ThrowOnError extends boolean = false>(options: Options<ListLocationLanguageProfilesData, ThrowOnError>): RequestResult<ListLocationLanguageProfilesResponses, ListLocationLanguageProfilesErrors, ThrowOnError> => (options.client ?? client).get<ListLocationLanguageProfilesResponses, ListLocationLanguageProfilesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListLocationLanguageProfilesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/{locationId}/profiles',
    ...options
});

/**
 * Language Profiles Schema (Legacy): Get
 *
 * Gets the schema.org-compliant schema for the requested Language Profile of a given Location. Schema will vary depending on the primary category of the Location.
 */
export const getLanguageProfilesSchema = <ThrowOnError extends boolean = false>(options: Options<GetLanguageProfilesSchemaData, ThrowOnError>): RequestResult<GetLanguageProfilesSchemaResponses, GetLanguageProfilesSchemaErrors, ThrowOnError> => (options.client ?? client).get<GetLanguageProfilesSchemaResponses, GetLanguageProfilesSchemaErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetLanguageProfilesSchemaResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/{locationId}/profiles/{languageCode}/schema',
    ...options
});

/**
 * Locations (Legacy): Get
 *
 * Gets the primary profile for a single Location
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const getLocation = <ThrowOnError extends boolean = false>(options: Options<GetLocationData, ThrowOnError>): RequestResult<GetLocationResponses, GetLocationErrors, ThrowOnError> => (options.client ?? client).get<GetLocationResponses, GetLocationErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetLocationResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/{locationId}',
    ...options
});

/**
 * Locations (Legacy): List
 *
 * Get multiple Locations (primary profile only). Filters are evaluated against all language profiles as well as the primary profile.
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const locationsList = <ThrowOnError extends boolean = false>(options: Options<LocationsListData, ThrowOnError>): RequestResult<LocationsListResponses, LocationsListErrors, ThrowOnError> => (options.client ?? client).get<LocationsListResponses, LocationsListErrors, ThrowOnError>({
    responseValidator: async (data) => await zLocationsListResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations',
    ...options
});

/**
 * Locations Schema (Legacy): Get
 *
 * Gets the schema.org-compliant schema for the primary profile of a single Location. Schema will vary depending on the primary category of the Location.
 */
export const getLocationSchema = <ThrowOnError extends boolean = false>(options: Options<GetLocationSchemaData, ThrowOnError>): RequestResult<GetLocationSchemaResponses, GetLocationSchemaErrors, ThrowOnError> => (options.client ?? client).get<GetLocationSchemaResponses, GetLocationSchemaErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetLocationSchemaResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/{locationId}/schema',
    ...options
});

/**
 * Locations (Legacy): GeoSearch
 *
 * Gets multiple Locations (primary profile only) near a given location, ordered by proximity to the location (if no other sort criteria are given) and restricted to a radius. Searches through all language profiles, including the primary profile.
 *
 * **NOTE:** Responses will contain resolved values for embedded fields
 *
 */
export const geoSearch = <ThrowOnError extends boolean = false>(options: Options<GeoSearchData, ThrowOnError>): RequestResult<GeoSearchResponses, GeoSearchErrors, ThrowOnError> => (options.client ?? client).get<GeoSearchResponses, GeoSearchErrors, ThrowOnError>({
    responseValidator: async (data) => await zGeoSearchResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/locations/geosearch',
    ...options
});

/**
 * Question: Create
 *
 *
 * Create a new Question.
 */
export const createQuestion = <ThrowOnError extends boolean = false>(options: Options<CreateQuestionData, ThrowOnError>): RequestResult<CreateQuestionResponses, CreateQuestionErrors, ThrowOnError> => (options.client ?? client).post<CreateQuestionResponses, CreateQuestionErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateQuestionResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/createQuestion',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Review: Create
 *
 *
 * Create a new Review.
 */
export const createReview = <ThrowOnError extends boolean = false>(options: Options<CreateReviewData, ThrowOnError>): RequestResult<CreateReviewResponses, CreateReviewErrors, ThrowOnError> => (options.client ?? client).post<CreateReviewResponses, CreateReviewErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateReviewResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/reviewSubmission',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Review: Delete
 *
 *
 * Delete a Review.
 */
export const deleteReview = <ThrowOnError extends boolean = false>(options: Options<DeleteReviewData, ThrowOnError>): RequestResult<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError> => (options.client ?? client).delete<DeleteReviewResponses, DeleteReviewErrors, ThrowOnError>({
    responseValidator: async (data) => await zDeleteReviewResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/reviewSubmission/{apiIdentifier}',
    ...options
});

/**
 * Review: Update
 *
 *
 * Update a Review.
 */
export const updateReview = <ThrowOnError extends boolean = false>(options: Options<UpdateReviewData, ThrowOnError>): RequestResult<UpdateReviewResponses, UpdateReviewErrors, ThrowOnError> => (options.client ?? client).put<UpdateReviewResponses, UpdateReviewErrors, ThrowOnError>({
    responseValidator: async (data) => await zUpdateReviewResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/reviewSubmission/{apiIdentifier}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Content: Get
 *
 * Retrieve records by ID from a Content Endpoint
 */
export const contentGet = <ThrowOnError extends boolean = false>(options: Options<ContentGetData, ThrowOnError>): RequestResult<ContentGetResponses, ContentGetErrors, ThrowOnError> => (options.client ?? client).get<ContentGetResponses, ContentGetErrors, ThrowOnError>({
    responseValidator: async (data) => await zContentGetResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/content/{endpoint}/{ids}',
    ...options
});

/**
 * Content: List
 *
 * List records from a Content Endpoint
 *
 * Content API provides the ability for a user to filter and sort records
 * by the contents of an indexed field. The filters and sorting parameters can
 * be provided as query parameters, in addition to the query parameters
 * documented here. If no filters are provided, the API returns all the records
 * (with pagination).
 *
 * For example, with the parameter **`name=Alice`**, only records where the
 * field **`name`** has value **`Alice`** will be returned.
 *
 * Similarly, adding the parameters **`name__in=Alice`** and **`name__in=Bob`**
 * will result in records with **`name`** equal to **`Alice`** OR **`name`**
 * equal to **`Bob`** being returned.
 *
 * ### Filters
 *
 * Filters are supported on Text, Numeric, Date and DateTime fields, although
 * not all filters are supported by all fields. It is also possible to filter
 * on an array of strings, or a string field nested in an array of objects. In
 * this case, the record will be present in the response if one of the field
 * values in the array matches the filter.
 *
 * Multiple filters on different fields and different filter types can be
 * combined in the same query. An indexed field with an object can be filtered
 * by using the dot notation, for example, **`address.city=Brooklyn`**.
 *
 * A number of different types of filters are supported.
 *
 * #### Equals
 *
 * This can be specified as simple query parameter.
 *
 * Supported Types: Text, Numeric, Date, DateTime, Fields within Arrays.
 *
 * *Example:*
 * Adding **`&name=Alice`** as a query parameter will return records where the
 * name field matches Alice.
 *
 *
 * #### Not Equals
 *
 * This can be specified with the **`neq`** modifier to the query parameter
 * key.
 *
 * Supported Types: Text, Numeric, Date, DateTime, Fields within Arrays.
 *
 * *Example:*
 * Adding **`&name__neq=Alice`** as a query parameter will return records where
 * the name field does not match Alice.
 *
 * #### Equals Any Of
 *
 * This is basically an `OR` clause for Equals on a given field. This can be
 * specified with the **`in`** modifier to the query parameter key.
 *
 * Supported Types: Text, Numeric, Date, DateTime, Fields within Arrays.
 *
 * *Example:*
 * Adding **`&name__in=Alice&name__in=Bob`** as a query parameter will return
 * records where the name field matches either Alice or Bob.
 *
 * #### Comparison
 *
 * The following comparison filters are supported:
 * * Greater Than with the modifier `gt`
 * * Greater Than Or Equals with the modifier `gte`
 * * Less Than with the modifier `lt`
 * * Less Than Or Equals with the modifier `lte`
 *
 * Supported Types: Numeric, Date, DateTime.
 *
 * *Example:*
 * Adding **`&createdDate__gt=2020-11-11&rating__gte=4`** as a query parameter
 * will return records where the `createdDate` is after `2020-11-11` and the
 * `rating` field has a value greater than or equal to `4`.
 *
 * #### GeoSearch
 *
 * Supports filtering to records for which the specified field is within the supplied radius to the supplied latitude and longitude.
 *
 * Supported Types: Coordinates (ex: `yextDisplayCoordinate`, `displayCoordinate`, etc.).
 *
 * GeoSearch queries are constructed by appending a `__geo` comparator to a coordinate field in the request. The details of the GeoSearch must then be included, comma separated, as part of the query value, optionally surrounded by parantheses.
 *
 * The following parameters are supported:
 * * The latitude of the point to geosearch from, specified as `lat`
 * * The longitude of the point to geosearch from, specified as `lon`
 * * The numeric radius from the point which results will be filtered to, specifed as `radius`
 * * The unit of measurement for the radius, specified as `unit`. One of `km`, `mi`, `m`, `ft`. Defaults to `mi`
 *
 * *Example:*
 * Adding **`&yextDisplayCoordinate__geo=(lat:40.740,lon:-73.987565,radius:50,unit:km)`** as a query parameter
 * will return records where the `yextDisplayCoordinate` field on the entities is within 50 km of the provided latitude and longitude.
 *
 * Like all other filters, the field which is being geosearched upon must be specified in the `fieldIndexes` of the endpoint definition.
 *
 * ### Sorting
 *
 * Content Endpoints support sorting by an indexed field. This can be enabled
 * by adding the `$sortBy` query parameter with field name as the value.
 * Optionally, the modifiers `asc` and `desc` can be added to indicate
 * sorting by ascending and descending orders respectively. If no modifier is
 * specified, the results will be returned in descending order.
 *
 * Currently, sorting is only supported on a single field per request.
 *
 * *Example:*
 * Adding **`&$sortBy__desc=createdDate`** as a query parameter will return
 * records with the most recent `createdDate` first.
 *
 * ### Additional Notes on Supported Types
 *
 * Indexes are supported on String, Numeric, Date and DateTime types. The set
 * of supported filters for each type is documented in the previous section.
 *
 * #### String
 *
 * Content Endpoints support indexing UTF-8 strings with a maximum length of
 * 256 characters.
 *
 * #### Date and DateTime
 *
 * * The timezone information on a DateTime, if present, will be stripped away
 * during indexing, without converting the time to another timezone.
 * * For indexing, the system expects to get [RFC3339 DateTime
 * format](https://datatracker.ietf.org/doc/html/rfc3339) for DateTimes and
 * `YYYY-MM-DD` for Dates.
 * * For querying, API accepts the following formats: `YYYY-MM-DD`,
 * `YYYY-MM-DDTHH`, `YYYY-MM-DDTHH:MM` and `YYYY-MM-DDTHH:MM:SS`.
 *
 */
export const contentList = <ThrowOnError extends boolean = false>(options: Options<ContentListData, ThrowOnError>): RequestResult<ContentListResponses, ContentListErrors, ThrowOnError> => (options.client ?? client).get<ContentListResponses, ContentListErrors, ThrowOnError>({
    responseValidator: async (data) => await zContentListResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/content/{endpoint}',
    ...options
});
