/**
 * Generates the yext-ts SDK from the vendored specs.
 *
 * For each of the 11 Yext APIs we run @hey-api/openapi-ts into `src/<module>/`,
 * emitting:
 *   - types.gen.ts   typed request/response models
 *   - zod.gen.ts     zod (v4) schemas for every model
 *   - sdk.gen.ts     fetch-based SDK functions, with zod request/response
 *                    validation wired in (validator: true)
 *   - client.gen.ts  a client-fetch client instance (imports the shared
 *                    @hey-api/client-fetch runtime; bundle: false)
 *   - index.ts       barrel re-export
 *
 * Then it writes the hand-maintained `src/index.ts` root barrel that namespaces
 * each module so consumers can `import { knowledge } from "yext-ts"`.
 *
 * Run with `pnpm generate`. The knowledge spec is ~6.3 MB so we raise the heap.
 */
import { existsSync } from "node:fs";
import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { createClient } from "@hey-api/openapi-ts";
import type { UserConfig } from "@hey-api/openapi-ts";

import { normalizeSpec } from "./normalize-spec.js";
import { SPECS } from "./specs.js";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const specsDir = join(root, "specs");
const srcDir = join(root, "src");
// Normalized specs (upstream quirks fixed) are written here and fed to the
// generator. Gitignored — the committed source of truth is `specs/`.
const normalizedDir = join(root, ".gen-specs");

async function generateModule(file: string, module: string, title: string) {
  const rawInput = join(specsDir, file);
  if (!existsSync(rawInput)) {
    throw new Error(`Missing spec ${rawInput}. Run \`pnpm fetch-specs\` first.`);
  }
  const output = join(srcDir, module);
  console.log(`\n▶ ${title}  (${file} → src/${module}/)`);

  // Normalize upstream quirks, then point the generator at the normalized copy.
  const normalized = normalizeSpec(JSON.parse(await readFile(rawInput, "utf8")));
  const input = join(normalizedDir, file);
  await writeFile(input, JSON.stringify(normalized), "utf8");

  const config = {
    input,
    output: {
      path: output,
      // Skip Prettier/lint here: the knowledge spec is huge and formatting it
      // on every run is slow. tsup/consumers don't care, and it stays valid TS.
      format: null,
      lint: null,
    },
    plugins: [
      "@hey-api/typescript",
      // Bundled fetch client (default). openapi-ts 0.98 emits SDK code against
      // the bundled runtime (ClientMeta/requestValidator); the standalone
      // @hey-api/client-fetch npm package is the legacy runtime and is NOT
      // compatible, so we let each module inline its own client/ runtime.
      "@hey-api/client-fetch",
      // zod v4 schemas (the installed zod is v4).
      "zod",
      // Wire zod into the SDK for RESPONSE validation only. Request validation
      // is intentionally off: the auth layer injects the required `v` (version)
      // and credential query params at the fetch layer (after the validator
      // would run), and Yext marks `v` required — so request validation would
      // reject every auto-authed call. Responses are still validated.
      { name: "@hey-api/sdk", validator: { request: false, response: true } },
    ],
  } satisfies UserConfig;

  await createClient(config);

  // The generated index.ts re-exports SDK functions + types, but not the
  // client-fetch `client` singleton nor the zod schemas. Expose both:
  //   - `client`  so consumers/auth can configure the client per module
  //   - `schemas` namespace so the zod schemas are usable for standalone
  //     validation (kept under a namespace to avoid flat name collisions with
  //     the type exports).
  await appendFile(
    join(output, "index.ts"),
    `\nexport { client } from "./client.gen.js";\n` +
      `export * as schemas from "./zod.gen.js";\n`,
    "utf8",
  );
}

function buildRootIndex(): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate.ts. Do not edit by hand.",
    "// Each Yext API is namespaced; import a single API for best tree-shaking",
    '// via its subpath, e.g. `import { listEntities } from "yext-ts/knowledge"`.',
    "",
  ];
  for (const { ns, module } of SPECS) {
    lines.push(`export * as ${ns} from "./${module}/index.js";`);
  }
  lines.push("");
  lines.push("// Auth + client configuration helpers (hand-written).");
  lines.push('export * from "./auth.js";');
  lines.push('export * from "./configure.js";');
  lines.push("");
  return lines.join("\n");
}

async function main() {
  await mkdir(srcDir, { recursive: true });
  await mkdir(normalizedDir, { recursive: true });

  for (const spec of SPECS) {
    await generateModule(spec.file, spec.module, spec.title);
  }

  await writeFile(join(srcDir, "index.ts"), buildRootIndex(), "utf8");
  console.log(`\n✅ Generated ${SPECS.length} modules + src/index.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
