// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CancelAllSubAccountServicesData, CancelAllSubAccountServicesErrors, CancelAllSubAccountServicesResponses, CancelServicesData, CancelServicesErrors, CancelServicesResponses, CancelSubAccountServicesData, CancelSubAccountServicesErrors, CancelSubAccountServicesResponses, CreateExistingLocationAddRequestData, CreateExistingLocationAddRequestErrors, CreateExistingLocationAddRequestResponses, CreateExistingSubAccountAddRequestData, CreateExistingSubAccountAddRequestErrors, CreateExistingSubAccountAddRequestResponses, CreateNewLocationAddRequestData, CreateNewLocationAddRequestErrors, CreateNewLocationAddRequestResponses, CreateProcessReviewAddRequestData, CreateProcessReviewAddRequestErrors, CreateProcessReviewAddRequestResponses, CreateSubAccountData, CreateSubAccountErrors, CreateSubAccountResponses, GetAccountData, GetAccountErrors, GetAccountResponses, GetAddRequestData, GetAddRequestErrors, GetAddRequestResponses, GetResourcesApplyRequestStatusData, GetResourcesApplyRequestStatusErrors, GetResourcesApplyRequestStatusResponses, GetSubAccountAddRequestData, GetSubAccountAddRequestErrors, GetSubAccountAddRequestResponses, ListAccountsData, ListAccountsErrors, ListAccountsResponses, ListAddRequestsData, ListAddRequestsErrors, ListAddRequestsResponses, ListAvailableServicesData, ListAvailableServicesErrors, ListAvailableServicesResponses, ListServicesData, ListServicesErrors, ListServicesResponses, ListSubAccountAddRequestsData, ListSubAccountAddRequestsErrors, ListSubAccountAddRequestsResponses, ListSubAccountServicesData, ListSubAccountServicesErrors, ListSubAccountServicesResponses, ResourcesApplyRequestData, ResourcesApplyRequestErrors, ResourcesApplyRequestResponses, UpdateAccountData, UpdateAccountErrors, UpdateAccountResponses } from './types.gen.js';
import { zCancelAllSubAccountServicesResponse, zCancelServicesResponse, zCancelSubAccountServicesResponse, zCreateExistingLocationAddRequestResponse, zCreateExistingSubAccountAddRequestResponse, zCreateNewLocationAddRequestResponse, zCreateProcessReviewAddRequestResponse, zCreateSubAccountResponse, zGetAccountResponse, zGetAddRequestResponse, zGetResourcesApplyRequestStatusResponse, zGetSubAccountAddRequestResponse, zListAccountsResponse, zListAddRequestsResponse, zListAvailableServicesResponse, zListServicesResponse, zListSubAccountAddRequestsResponse, zListSubAccountServicesResponse, zResourcesApplyRequestResponse2, zUpdateAccountResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Available Services: List
 *
 * Return list of services available to you under your agreements
 */
export const listAvailableServices = <ThrowOnError extends boolean = false>(options: Options<ListAvailableServicesData, ThrowOnError>): RequestResult<ListAvailableServicesResponses, ListAvailableServicesErrors, ThrowOnError> => (options.client ?? client).get<ListAvailableServicesResponses, ListAvailableServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListAvailableServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/availableservices',
    ...options
});

/**
 * Add Requests: Create (New Location)
 *
 * Request that a new location be added and services added to it. The location is created only if the "status" field returned is "COMPLETE". In most cases, the "status" returned in the Add Request: Create response will be "SUBMITTED". For a list and explanation of each possible "status", please see the [**Add Requests: Get (Location)**](#operation/getAddRequest) section.
 *
 * To receive real-time updates on the status of your Add Request, we recommend that you configure the [**Add Request Update: Webhook**](../webhooks/index.html#operation/addRequestWebhook) in the Developer Console (see the [**Configure Webhooks**](http://developer.yext.com/docs/guides/configure-webhooks/) guide for more information). Alternatively, use the [**Add Requests: Get (Location)**](#operation/getAddRequest) call to determine the current Add Request "status".
 *
 */
export const createNewLocationAddRequest = <ThrowOnError extends boolean = false>(options: Options<CreateNewLocationAddRequestData, ThrowOnError>): RequestResult<CreateNewLocationAddRequestResponses, CreateNewLocationAddRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateNewLocationAddRequestResponses, CreateNewLocationAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateNewLocationAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/newlocationaddrequests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Requests: Create (Existing Location)
 *
 * Request that one or more available services be added to an existing location.
 */
export const createExistingLocationAddRequest = <ThrowOnError extends boolean = false>(options: Options<CreateExistingLocationAddRequestData, ThrowOnError>): RequestResult<CreateExistingLocationAddRequestResponses, CreateExistingLocationAddRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateExistingLocationAddRequestResponses, CreateExistingLocationAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateExistingLocationAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/existinglocationaddrequests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Requests: Create (Existing Account)
 *
 * Request that one or more available services be added (or increased in quantity) to an existing account.
 */
export const createExistingSubAccountAddRequest = <ThrowOnError extends boolean = false>(options: Options<CreateExistingSubAccountAddRequestData, ThrowOnError>): RequestResult<CreateExistingSubAccountAddRequestResponses, CreateExistingSubAccountAddRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateExistingSubAccountAddRequestResponses, CreateExistingSubAccountAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateExistingSubAccountAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/existingsubaccountaddrequests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Services: Cancel (Location)
 *
 * Cancel one or more active services provisioned on the location.
 *
 * **NOTE:** If you have added location services under a sub-account, use this endpoint on your *main account* to cancel them.
 *
 */
export const cancelServices = <ThrowOnError extends boolean = false>(options: Options<CancelServicesData, ThrowOnError>): RequestResult<CancelServicesResponses, CancelServicesErrors, ThrowOnError> => (options.client ?? client).post<CancelServicesResponses, CancelServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zCancelServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/cancelservices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Services: Cancel (Account)
 *
 * Cancel (or decrease the quantity of) one or more active services provisioned on the account.
 *
 * **NOTE:** If you have added services to a sub-account, use this endpoint on your *main account* to cancel them.
 *
 */
export const cancelSubAccountServices = <ThrowOnError extends boolean = false>(options: Options<CancelSubAccountServicesData, ThrowOnError>): RequestResult<CancelSubAccountServicesResponses, CancelSubAccountServicesErrors, ThrowOnError> => (options.client ?? client).post<CancelSubAccountServicesResponses, CancelSubAccountServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zCancelSubAccountServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/cancelsubaccountservices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Services: Cancel All (Account)
 *
 * Cancel all active services (all quantities) provisioned on the account.
 *
 * **NOTE:** If you have added services to a sub-account, use this endpoint on your *main account* to cancel all of them.
 *
 */
export const cancelAllSubAccountServices = <ThrowOnError extends boolean = false>(options: Options<CancelAllSubAccountServicesData, ThrowOnError>): RequestResult<CancelAllSubAccountServicesResponses, CancelAllSubAccountServicesErrors, ThrowOnError> => (options.client ?? client).post<CancelAllSubAccountServicesResponses, CancelAllSubAccountServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zCancelAllSubAccountServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/cancelallsubaccountservices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Requests: Process (Sandbox API Only)
 *
 * Request that an add request in REVIEW be processed to COMPLETE, CANCELED, or FAILED. Only applicable for location add requests.
 */
export const createProcessReviewAddRequest = <ThrowOnError extends boolean = false>(options: Options<CreateProcessReviewAddRequestData, ThrowOnError>): RequestResult<CreateProcessReviewAddRequestResponses, CreateProcessReviewAddRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateProcessReviewAddRequestResponses, CreateProcessReviewAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateProcessReviewAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/processaddrequest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Requests: List (Location)
 *
 * Get all of the add requests in the account that were created for locations. The response includes both New Location Add Requests and Existing Location Add Requests.
 *
 * Possible `status` values for each add request:
 * * SUBMITTED - The request has been submitted for processing. Updated status should be available soon, usually within seconds.
 * * PROCESSING - The request is currently being processed. Updated status should be available soon, usually within seconds.
 * * COMPLETE - The request was successfully processed and service was added. You can verify this by retrieving services for the location.
 * * CANCELED - The request was purposefully canceled by Yext and was not processed. Details are available in the *results* field.
 * * REVIEW - The request is being reviewed by Yext, most likely because this location may be a duplicate of another location already
 * receiving this service through Yext. Once the review is complete, *status* will be updated to either CANCELED or COMPLETE.
 * * FAILED - Processing the request failed due to a technical issue. Details may be available in the *statusDetail* field. No changes were made to your account, so you can
 * try the request again.
 *
 */
export const listAddRequests = <ThrowOnError extends boolean = false>(options: Options<ListAddRequestsData, ThrowOnError>): RequestResult<ListAddRequestsResponses, ListAddRequestsErrors, ThrowOnError> => (options.client ?? client).get<ListAddRequestsResponses, ListAddRequestsErrors, ThrowOnError>({
    responseValidator: async (data) => await zListAddRequestsResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/addrequests',
    ...options
});

/**
 * Add Requests: Get (Location)
 *
 * Get status information about an add request that was previously created for a location.
 *
 * Possible statuses:
 * * SUBMITTED - The request has been submitted for processing. Updated status should be available soon, usually within seconds.
 * * PROCESSING - The request is currently being processed. Updated status should be available soon, usually within seconds.
 * * COMPLETE - The request was successfully processed and service was added. You can verify this by retrieving services for the location.
 * * CANCELED - The request was purposefully canceled by Yext and was not processed. Details are available in the *results* field.
 * * REVIEW - The request is being reviewed by Yext, most likely because this location may be a duplicate of another location already
 * receiving this service through Yext. Once the review is complete, *status* will be updated to either CANCELED or COMPLETE.
 * * FAILED - Processing the request failed due to a technical issue. Details may be available in the *statusDetail* field. No changes were made to your account, so you can
 * try the request again.
 *
 */
export const getAddRequest = <ThrowOnError extends boolean = false>(options: Options<GetAddRequestData, ThrowOnError>): RequestResult<GetAddRequestResponses, GetAddRequestErrors, ThrowOnError> => (options.client ?? client).get<GetAddRequestResponses, GetAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/addrequests/{addRequestId}',
    ...options
});

/**
 * Add Requests: List (Sub-Account)
 *
 * Get all of the add requests in the account that were created for sub-accounts.
 *
 * Possible `status` values for each add request:
 * * SUBMITTED - The request has been submitted for processing. Updated status should be available soon, usually within seconds.
 * * PROCESSING - The request is currently being processed. Updated status should be available soon, usually within seconds.
 * * COMPLETE - The request was successfully processed and service was added. You can verify this by retrieving services for the sub-account.
 * * CANCELED - The request was purposefully canceled by Yext and was not processed. Details are available in the *results* field.
 * * FAILED - Processing the request failed due to a technical issue. Details may be available in the *statusDetail* field. No changes were made to your account, so you can
 * try the request again.
 *
 */
export const listSubAccountAddRequests = <ThrowOnError extends boolean = false>(options: Options<ListSubAccountAddRequestsData, ThrowOnError>): RequestResult<ListSubAccountAddRequestsResponses, ListSubAccountAddRequestsErrors, ThrowOnError> => (options.client ?? client).get<ListSubAccountAddRequestsResponses, ListSubAccountAddRequestsErrors, ThrowOnError>({
    responseValidator: async (data) => await zListSubAccountAddRequestsResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/subaccountaddrequests',
    ...options
});

/**
 * Add Requests: Get (Sub-Account)
 *
 * Get status information about an add request that was previously created for a sub-account.
 *
 * Possible statuses:
 * * SUBMITTED - The request has been submitted for processing. Updated status should be available soon, usually within seconds.
 * * PROCESSING - The request is currently being processed. Updated status should be available soon, usually within seconds.
 * * COMPLETE - The request was successfully processed and service was added. You can verify this by retrieving services for the sub-account.
 * * CANCELED - The request was purposefully canceled by Yext and was not processed. Details are available in the *results* field.
 * * FAILED - Processing the request failed due to a technical issue. Details may be available in the *statusDetail* field. No changes were made to your account, so you can
 * try the request again.
 *
 */
export const getSubAccountAddRequest = <ThrowOnError extends boolean = false>(options: Options<GetSubAccountAddRequestData, ThrowOnError>): RequestResult<GetSubAccountAddRequestResponses, GetSubAccountAddRequestErrors, ThrowOnError> => (options.client ?? client).get<GetSubAccountAddRequestResponses, GetSubAccountAddRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetSubAccountAddRequestResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/subaccountaddrequests/{addRequestId}',
    ...options
});

/**
 * Services: List (Location)
 *
 * Retrieve a list of all services provisioned on a location.
 *
 * **NOTE:** If you have added location services under sub-accounts, they will be returned from this endpoint on your *main account*.
 *
 */
export const listServices = <ThrowOnError extends boolean = false>(options: Options<ListServicesData, ThrowOnError>): RequestResult<ListServicesResponses, ListServicesErrors, ThrowOnError> => (options.client ?? client).get<ListServicesResponses, ListServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/services',
    ...options
});

/**
 * Services: List (Sub-Account)
 *
 * Retrieve a list of all services provisioned on a sub-account.
 *
 * **NOTE:** If you have added services to sub-accounts, they will be returned from this endpoint on your *main account*.
 *
 */
export const listSubAccountServices = <ThrowOnError extends boolean = false>(options: Options<ListSubAccountServicesData, ThrowOnError>): RequestResult<ListSubAccountServicesResponses, ListSubAccountServicesErrors, ThrowOnError> => (options.client ?? client).get<ListSubAccountServicesResponses, ListSubAccountServicesErrors, ThrowOnError>({
    responseValidator: async (data) => await zListSubAccountServicesResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/subaccountservices',
    ...options
});

/**
 * Accounts: Create Sub-Account
 *
 * Request to create a new empty sub-account under this account.
 */
export const createSubAccount = <ThrowOnError extends boolean = false>(options: Options<CreateSubAccountData, ThrowOnError>): RequestResult<CreateSubAccountResponses, CreateSubAccountErrors, ThrowOnError> => (options.client ?? client).post<CreateSubAccountResponses, CreateSubAccountErrors, ThrowOnError>({
    responseValidator: async (data) => await zCreateSubAccountResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/createsubaccount',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Resources Apply Request: Create (Account)
 *
 * Create a request to asynchronously apply resources using the URL of a GitHub repository.
 *
 */
export const resourcesApplyRequest = <ThrowOnError extends boolean = false>(options: Options<ResourcesApplyRequestData, ThrowOnError>): RequestResult<ResourcesApplyRequestResponses, ResourcesApplyRequestErrors, ThrowOnError> => (options.client ?? client).post<ResourcesApplyRequestResponses, ResourcesApplyRequestErrors, ThrowOnError>({
    responseValidator: async (data) => await zResourcesApplyRequestResponse2.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/resourcesapplyrequests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Resources Apply Request Status: Get (Account)
 *
 * Make a request to get the status of the Resources Apply Request.
 *
 */
export const getResourcesApplyRequestStatus = <ThrowOnError extends boolean = false>(options: Options<GetResourcesApplyRequestStatusData, ThrowOnError>): RequestResult<GetResourcesApplyRequestStatusResponses, GetResourcesApplyRequestStatusErrors, ThrowOnError> => (options.client ?? client).get<GetResourcesApplyRequestStatusResponses, GetResourcesApplyRequestStatusErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetResourcesApplyRequestStatusResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}/resourcesapplyrequests/{requestId}',
    ...options
});

/**
 * Accounts: List
 *
 * List all accounts that you have access to. Unless you are in Partner Portal mode, this will only be your own account.
 */
export const listAccounts = <ThrowOnError extends boolean = false>(options?: Options<ListAccountsData, ThrowOnError>): RequestResult<ListAccountsResponses, ListAccountsErrors, ThrowOnError> => (options?.client ?? client).get<ListAccountsResponses, ListAccountsErrors, ThrowOnError>({
    responseValidator: async (data) => await zListAccountsResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts',
    ...options
});

/**
 * Accounts: Get
 *
 * Get details for an account
 */
export const getAccount = <ThrowOnError extends boolean = false>(options: Options<GetAccountData, ThrowOnError>): RequestResult<GetAccountResponses, GetAccountErrors, ThrowOnError> => (options.client ?? client).get<GetAccountResponses, GetAccountErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetAccountResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}',
    ...options
});

/**
 * Accounts: Update
 *
 * Update an account's name or ID
 */
export const updateAccount = <ThrowOnError extends boolean = false>(options: Options<UpdateAccountData, ThrowOnError>): RequestResult<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError> => (options.client ?? client).put<UpdateAccountResponses, UpdateAccountErrors, ThrowOnError>({
    responseValidator: async (data) => await zUpdateAccountResponse.parseAsync(data),
    security: [{
            in: 'query',
            name: 'api_key',
            type: 'apiKey'
        }, { name: 'api-key', type: 'apiKey' }],
    url: '/accounts/{accountId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
