// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { GetEclListData, GetEclListErrors, GetEclListResponses } from './types.gen.js';
import { zGetEclListResponse } from './zod.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get List
 *
 * Use Get List to retrieve Enhanced Content List (ECL) content in the following use cases:
 * 1. Fetch the HTML for a specific type of List.
 * * **Use listingId, template**
 * * Response will be rendered into a template and returned for direct display to the user
 * 2. Fetch the structured data (JSON) for a specific List
 * * **Use listingId, listId**
 * 3. Fetch the structured data (JSON) for a specific type of List
 * * **Use listingId, type**
 * 4. Fetch the structured data (JSON) for all Lists associated with a listing
 * * **Use listingId**
 *
 */
export const getEclList = <ThrowOnError extends boolean = false>(options?: Options<GetEclListData, ThrowOnError>): RequestResult<GetEclListResponses, GetEclListErrors, ThrowOnError> => (options?.client ?? client).get<GetEclListResponses, GetEclListErrors, ThrowOnError>({
    responseValidator: async (data) => await zGetEclListResponse.parseAsync(data),
    url: '/lists',
    ...options
});
