// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://lists.yext-pub.com' | (string & {});
};

export type Section = {
    /**
     * Name of the section.  Here are examples of section names for each type:
     * * Menu: [Appetizer, Entree, Dessert]
     * * Products: [Kenmore, Craftsman]
     * * Bios: [Dentists, Pediatrics]
     * * Events: [""]
     * * The name field may contain the empty string (""), which indicates that the enclosed items were not assigned to a section.
     * Events in a single list will never be divided into multiple sections. All events in a given list will always be in a single section with the name "", in order to preserve the structure used in the other list types.
     *
     */
    name?: string;
    /**
     * Description of the section
     */
    description?: string;
    /**
     * One of:
     * * A list of Menu Items
     * * A list of Bios
     * * A list of Products
     * * A list of Events
     * **See examples of each above**
     *
     */
    items?: Array<unknown>;
};

export type Ecl = {
    /**
     * ID of this list (Yext-assigned)
     */
    id?: string;
    /**
     * Name of the list.  Here are examples of list names for each type:
     * * Menu: [Breakfast, Lunch, Dinner]
     * * Products: [Mens, Womens]
     * * Bios: [General Practitioners, Specialists]
     * * Events: [Concerts, Workshops]
     *
     */
    name?: string;
    /**
     * The label for this list type, as it should appear on the list type's button or link in the PowerListing (e.g., Our Doctors for Bios, Store Events for Events)
     * Defaults are:
     * * Menu
     * * Products
     * * Bios
     * * Events
     *
     */
    description?: string;
    type?: 'MENU' | 'PRODUCTS' | 'BIOS' | 'EVENTS';
    /**
     * The number of items in the list
     *
     */
    size?: number;
    /**
     * The URL of the source the list's content is retrieved from
     *
     */
    sourceUrl?: string;
    /**
     * The list's sections
     *
     */
    sections?: Array<Section>;
};

/**
 * Publisher secure ID. This value will be provided to you.
 *
 */
export type Pid = string;

/**
 * Publisher listing ID
 *
 */
export type ListingId = string;

/**
 * The Yext listing ID
 *
 */
export type YextId = string;

/**
 * ECL ID (Yext-assigned)
 *
 */
export type ListId = string;

/**
 * Type of lists to return
 *
 */
export type Type = 'MENU' | 'PRODUCTS' | 'BIOS' | 'EVENTS';

/**
 * This parameter specifies the template to use when rendering the List content.
 * Yext will provide a list of your available templates. Yext configures each template with the type of data that it accepts -- for example, the template "mobile-menu" may be configured to render all Lists on a listing of type MENU.
 * * If no template is specified, all List data will be rendered using a default template
 * * Required if fetching HTML
 *
 */
export type Template = string;

/**
 * An alternative way to specify the desired content type of the response
 *
 */
export type Format = 'html' | 'json';

export type GetEclListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Publisher secure ID. This value will be provided to you.
         *
         */
        pid?: string;
        /**
         * Publisher listing ID
         *
         */
        listingId?: string;
        /**
         * The Yext listing ID
         *
         */
        yextId?: string;
        /**
         * ECL ID (Yext-assigned)
         *
         */
        listId?: string;
        /**
         * Type of lists to return
         *
         */
        type?: 'MENU' | 'PRODUCTS' | 'BIOS' | 'EVENTS';
        /**
         * This parameter specifies the template to use when rendering the List content.
         * Yext will provide a list of your available templates. Yext configures each template with the type of data that it accepts -- for example, the template "mobile-menu" may be configured to render all Lists on a listing of type MENU.
         * * If no template is specified, all List data will be rendered using a default template
         * * Required if fetching HTML
         *
         */
        template?: string;
        /**
         * An alternative way to specify the desired content type of the response
         *
         */
        format?: 'html' | 'json';
    };
    url: '/lists';
};

export type GetEclListErrors = {
    /**
     * Bad request (Incorrect Format)
     */
    400: unknown;
};

export type GetEclListResponses = {
    /**
     * GetECLSuccess
     *
     * (JSON Format)
     */
    200: {
        response?: Ecl;
    };
};

export type GetEclListResponse = GetEclListResponses[keyof GetEclListResponses];
