// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zSection = z.object({
    name: z.string().optional(),
    description: z.string().optional(),
    items: z.array(z.unknown()).optional()
});

export const zEcl = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    type: z.enum([
        'MENU',
        'PRODUCTS',
        'BIOS',
        'EVENTS'
    ]).optional(),
    size: z.int().optional(),
    sourceUrl: z.string().optional(),
    sections: z.array(zSection).optional()
});

/**
 * Publisher secure ID. This value will be provided to you.
 *
 */
export const zPid = z.string();

/**
 * Publisher listing ID
 *
 */
export const zListingId = z.string();

/**
 * The Yext listing ID
 *
 */
export const zYextId = z.string();

/**
 * ECL ID (Yext-assigned)
 *
 */
export const zListId = z.string();

/**
 * Type of lists to return
 *
 */
export const zType = z.enum([
    'MENU',
    'PRODUCTS',
    'BIOS',
    'EVENTS'
]);

/**
 * This parameter specifies the template to use when rendering the List content.
 * Yext will provide a list of your available templates. Yext configures each template with the type of data that it accepts -- for example, the template "mobile-menu" may be configured to render all Lists on a listing of type MENU.
 * * If no template is specified, all List data will be rendered using a default template
 * * Required if fetching HTML
 *
 */
export const zTemplate = z.string();

/**
 * An alternative way to specify the desired content type of the response
 *
 */
export const zFormat = z.enum(['html', 'json']);

export const zGetEclListQuery = z.object({
    pid: z.string().optional(),
    listingId: z.string().optional(),
    yextId: z.string().optional(),
    listId: z.string().optional(),
    type: z.enum([
        'MENU',
        'PRODUCTS',
        'BIOS',
        'EVENTS'
    ]).optional(),
    template: z.string().optional(),
    format: z.enum(['html', 'json']).optional()
});

/**
 * GetECLSuccess
 *
 * (JSON Format)
 */
export const zGetEclListResponse = z.object({
    response: zEcl.optional()
});
